project:
  type: book
  output-dir: .
  execute-dir: project
engine: knitr
execute:
  freeze: auto
  cache: true
book:
  title: "Elements of Statistical Computation"
  repo-url: "https://github.com/longhaiSK/compstat"
  output-file: CompStat-LLi
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/unit01_intro_course.qmd
    - chapters/unit02_introduction_longer.qmd
    - chapters/unit03_comparith.qmd
    - chapters/Unit04_monte_carlo.qmd
    - chapters/unit05_MLE.qmd
    - chapters/unit06_em.qmd
    - chapters/unit07_bayesian_inference.qmd
    - chapters/unit08_integral.qmd
    - chapters/unit09_laplace.qmd
    - chapters/unit10_rejection_sampling.qmd
    - chapters/unit11_importance_sampling.qmd
    - chapters/unit12_mcmc.qmd
  appendices: 
    - gallery.qmd
format:
  custombook-html: default
