project:
  type: book
  output-dir: .
  execute-dir: project
engine: knitr
execute:
  freeze: auto
  cache: true
book:
  title: "Elements of Computational Techniques in Statistics"
  repo-url: "https://github.com/longhaiSK/compstat"
  output-file: CompStat-LLi
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/unit01_intro_course.qmd
    - chapters/unit02_introduction_longer.qmd
    - chapters/unit03_comparith.qmd
    - chapters/unit04_sampling_basics.qmd
    - chapters/unit05_simulation.qmd
    - chapters/unit06_MLE.qmd
    - chapters/unit08_em.qmd
    - chapters/unit07_bayesian_inference.qmd
    - chapters/unit09_integral.qmd
    - chapters/unit10_laplace.qmd
    - chapters/unit11_rejection_sampling.qmd
    - chapters/unit12_importance_sampling.qmd
    - chapters/unit12_mcmc.qmd
format:
  custombook-html: default
