project:
  type: book
  output-dir: .
engine: knitr
book:
  title: "Computational Statistics"
  output-file: CompStatLLi
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/unit01_introduction_longer.qmd
    - chapters/unit02_comparith.qmd
    - chapters/unit03_sampling_basics.qmd
    - chapters/unit04_simulation.qmd
    - chapters/unit05_MLE1.qmd
    - chapters/unit06_MLEm.qmd
    - chapters/unit07_em.qmd
    - chapters/unit08_integral.qmd
    - chapters/unit09_laplace.qmd
    - chapters/unit10_rejection_sampling.qmd
    - chapters/unit11_importance_sampling.qmd
    - chapters/unit11_mcmc_intro.qmd
    - chapters/unit12_gibbs.qmd
    - chapters/unit14_MHsampling.qmd
    - chapters/unit15_jags.qmd
    - chapters/unit16_stan.qmd
format:
  custombook-html: default
