<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Longhai Li">
<meta name="dcterms.date" content="2026-09-18">

<title>7&nbsp; Introduction to Bayesian Inference – Elements of Statistical Computation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f79c7fb6db380d32be398468f2fb58cf.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a7b5894d5a4c39c6aa3484761f021c1f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/custombook-1.0.0/num_eq.js"></script>
<script src="../site_libs/quarto-contrib/custombook-1.0.0/merge-toc.js"></script>
<link href="../site_libs/quarto-contrib/custombook-1.0.0/bookstyles.css" rel="stylesheet">
<meta name="shinylive:serviceworker_dir" content="..">
<script src="../site_libs/quarto-contrib/shinylive-0.10.12/shinylive/load-shinylive-sw.js" type="module"></script>
<script src="../site_libs/quarto-contrib/shinylive-0.10.12/shinylive/run-python-blocks.js" type="module"></script>
<link href="../site_libs/quarto-contrib/shinylive-0.10.12/shinylive/shinylive.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/shinylive-quarto-css/shinylive-quarto.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/unit07_bayesian_inference.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Bayesian Inference</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Elements of Statistical Computation</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/longhaiSK/compstat" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit01_intro_course.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Statistical Computation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit02_introduction_longer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R and Quarto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit03_comparith.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Computer Arithmetic</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/Unit04_monte_carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Numbers and Monte Carlo Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit05_MLE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Optimization for Maximum Likelihood Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit06_em.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">EM Algorithms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit07_bayesian_inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Bayesian Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit08_integral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Numerical Quadrature</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit09_laplace.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Laplace Approximation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit10_rejection_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Rejection Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit11_importance_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Importance Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit12_mcmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Markov Chain Monte Carlo</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../gallery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">List of Figures, Tables, and Apps</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-bayesian-framework" id="toc-the-bayesian-framework" class="nav-link active" data-scroll-target="#the-bayesian-framework"><span class="header-section-number">7.1</span> The Bayesian Framework</a></li>
  <li><a href="#summarizing-the-posterior" id="toc-summarizing-the-posterior" class="nav-link" data-scroll-target="#summarizing-the-posterior"><span class="header-section-number">7.2</span> Summarizing the Posterior</a>
  <ul>
  <li><a href="#point-estimates-from-loss-functions" id="toc-point-estimates-from-loss-functions" class="nav-link" data-scroll-target="#point-estimates-from-loss-functions"><span class="header-section-number">7.2.1</span> Point estimates from loss functions</a></li>
  <li><a href="#posterior-prediction" id="toc-posterior-prediction" class="nav-link" data-scroll-target="#posterior-prediction"><span class="header-section-number">7.2.2</span> Posterior prediction</a></li>
  </ul></li>
  <li><a href="#example-bernoulli-data-with-a-beta-prior" id="toc-example-bernoulli-data-with-a-beta-prior" class="nav-link" data-scroll-target="#example-bernoulli-data-with-a-beta-prior"><span class="header-section-number">7.3</span> Example: Bernoulli Data with a Beta Prior</a>
  <ul>
  <li><a href="#prior" id="toc-prior" class="nav-link" data-scroll-target="#prior"><span class="header-section-number">7.3.1</span> Prior</a></li>
  <li><a href="#likelihood-and-posterior" id="toc-likelihood-and-posterior" class="nav-link" data-scroll-target="#likelihood-and-posterior"><span class="header-section-number">7.3.2</span> Likelihood and posterior</a></li>
  <li><a href="#posterior-summaries" id="toc-posterior-summaries" class="nav-link" data-scroll-target="#posterior-summaries"><span class="header-section-number">7.3.3</span> Posterior summaries</a></li>
  <li><a href="#the-marginal-likelihood-in-closed-form" id="toc-the-marginal-likelihood-in-closed-form" class="nav-link" data-scroll-target="#the-marginal-likelihood-in-closed-form"><span class="header-section-number">7.3.4</span> The marginal likelihood in closed form</a></li>
  <li><a href="#posterior-predictive-in-closed-form" id="toc-posterior-predictive-in-closed-form" class="nav-link" data-scroll-target="#posterior-predictive-in-closed-form"><span class="header-section-number">7.3.5</span> Posterior predictive, in closed form</a></li>
  <li><a href="#worked-numbers-the-complete-inference-output" id="toc-worked-numbers-the-complete-inference-output" class="nav-link" data-scroll-target="#worked-numbers-the-complete-inference-output"><span class="header-section-number">7.3.6</span> Worked numbers: the complete inference output</a></li>
  </ul></li>
  <li><a href="#example-poisson-data-with-a-gamma-prior" id="toc-example-poisson-data-with-a-gamma-prior" class="nav-link" data-scroll-target="#example-poisson-data-with-a-gamma-prior"><span class="header-section-number">7.4</span> Example: Poisson Data with a Gamma Prior</a>
  <ul>
  <li><a href="#prior-1" id="toc-prior-1" class="nav-link" data-scroll-target="#prior-1"><span class="header-section-number">7.4.1</span> Prior</a></li>
  <li><a href="#likelihood-and-posterior-1" id="toc-likelihood-and-posterior-1" class="nav-link" data-scroll-target="#likelihood-and-posterior-1"><span class="header-section-number">7.4.2</span> Likelihood and posterior</a></li>
  <li><a href="#the-marginal-likelihood-in-closed-form-1" id="toc-the-marginal-likelihood-in-closed-form-1" class="nav-link" data-scroll-target="#the-marginal-likelihood-in-closed-form-1"><span class="header-section-number">7.4.3</span> The marginal likelihood in closed form</a></li>
  <li><a href="#posterior-predictive-in-closed-form-1" id="toc-posterior-predictive-in-closed-form-1" class="nav-link" data-scroll-target="#posterior-predictive-in-closed-form-1"><span class="header-section-number">7.4.4</span> Posterior predictive, in closed form</a></li>
  <li><a href="#worked-numbers-the-complete-inference-output-1" id="toc-worked-numbers-the-complete-inference-output-1" class="nav-link" data-scroll-target="#worked-numbers-the-complete-inference-output-1"><span class="header-section-number">7.4.5</span> Worked numbers: the complete inference output</a></li>
  <li><a href="#overdispersion-visualized" id="toc-overdispersion-visualized" class="nav-link" data-scroll-target="#overdispersion-visualized"><span class="header-section-number">7.4.6</span> Overdispersion, visualized</a></li>
  </ul></li>
  <li><a href="#example-normal-data-with-a-normal-prior-known-variance" id="toc-example-normal-data-with-a-normal-prior-known-variance" class="nav-link" data-scroll-target="#example-normal-data-with-a-normal-prior-known-variance"><span class="header-section-number">7.5</span> Example: Normal Data with a Normal Prior (Known Variance)</a>
  <ul>
  <li><a href="#prior-2" id="toc-prior-2" class="nav-link" data-scroll-target="#prior-2"><span class="header-section-number">7.5.1</span> Prior</a></li>
  <li><a href="#likelihood-and-posterior-2" id="toc-likelihood-and-posterior-2" class="nav-link" data-scroll-target="#likelihood-and-posterior-2"><span class="header-section-number">7.5.2</span> Likelihood and posterior</a></li>
  <li><a href="#the-marginal-likelihood-in-closed-form-2" id="toc-the-marginal-likelihood-in-closed-form-2" class="nav-link" data-scroll-target="#the-marginal-likelihood-in-closed-form-2"><span class="header-section-number">7.5.3</span> The marginal likelihood in closed form</a></li>
  <li><a href="#posterior-predictive-in-closed-form-2" id="toc-posterior-predictive-in-closed-form-2" class="nav-link" data-scroll-target="#posterior-predictive-in-closed-form-2"><span class="header-section-number">7.5.4</span> Posterior predictive, in closed form</a></li>
  <li><a href="#worked-numbers-the-complete-inference-output-2" id="toc-worked-numbers-the-complete-inference-output-2" class="nav-link" data-scroll-target="#worked-numbers-the-complete-inference-output-2"><span class="header-section-number">7.5.5</span> Worked numbers: the complete inference output</a></li>
  <li><a href="#overdispersion-visualized-1" id="toc-overdispersion-visualized-1" class="nav-link" data-scroll-target="#overdispersion-visualized-1"><span class="header-section-number">7.5.6</span> Overdispersion, visualized</a></li>
  </ul></li>
  <li><a href="#sec-bayes-explorer" id="toc-sec-bayes-explorer" class="nav-link" data-scroll-target="#sec-bayes-explorer"><span class="header-section-number">7.6</span> Explore it interactively</a></li>
  <li><a href="#where-computation-enters" id="toc-where-computation-enters" class="nav-link" data-scroll-target="#where-computation-enters"><span class="header-section-number">7.7</span> Where Computation Enters</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">7.8</span> Summary</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Bayesian Inference</span></h1>
</div>



<div class="quarto-title-meta column-page-right">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Longhai Li </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The last three chapters found a single best-fitting parameter value — the MLE — by optimization: gradient methods and Newton’s method for a smooth log-likelihood, EM when part of the data is missing. Bayesian inference asks a different question: not just <em>where</em> is the best <span class="math inline">\(\theta\)</span>, but how uncertain are we about it, given whatever we already believed before seeing the data? The answer is a full distribution over <span class="math inline">\(\theta\)</span>, not a point, and extracting anything useful from that distribution — a mean, a probability, a prediction — is almost always a matter of computing an integral or an optimization. That is why Bayesian inference sets the agenda for the rest of this book: numerical quadrature, Laplace’s method, rejection sampling, importance sampling, and Markov chain Monte Carlo are all, at bottom, different strategies for computing with a posterior distribution that has no closed form.</p>
<section id="the-bayesian-framework" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-bayesian-framework"><span class="header-section-number">7.1</span> The Bayesian Framework</h2>
<p>Bayesian inference treats the unknown parameter <span class="math inline">\(\theta\)</span> itself as a random variable and proceeds in four steps:</p>
<ol type="1">
<li><strong>Specify a prior</strong> <span class="math inline">\(\pi(\theta)\)</span> — what is known or believed about <span class="math inline">\(\theta\)</span> before seeing any data.</li>
<li><strong>Specify a probability model for the data</strong>, <span class="math inline">\(P(y_1,\ldots,y_n\mid\theta)\)</span>, exactly the sampling model used to build a likelihood in the MLE chapters.</li>
<li><strong>Find the posterior</strong> by Bayes’ rule, <span class="math display">\[
P(\theta\mid y_{1:n}) = \frac{P(y_{1:n}\mid\theta)\,\pi(\theta)}
{\displaystyle\int P(y_{1:n}\mid\theta)\,\pi(\theta)\,d\theta}.
\]</span></li>
<li><strong>Interpret the posterior</strong>: summarize <span class="math inline">\(\theta\)</span>, make predictions.</li>
</ol>
<p>Writing <span class="math inline">\(L(\theta) = P(y_{1:n}\mid\theta)\)</span> for the likelihood and <span class="math inline">\(f(\theta) = L(\theta)\pi(\theta)\)</span> for the <strong>unnormalized posterior</strong> — the notation used throughout the rest of this book — step 3 becomes <span class="math display">\[
P(\theta\mid y_{1:n}) = \frac{f(\theta)}{P(y_{1:n})}, \qquad
P(y_{1:n}) = \int f(\theta)\,d\theta.
\]</span> <span class="math inline">\(P(y_{1:n})\)</span>, the <strong>marginal likelihood</strong>, is the likelihood averaged over the prior rather than maximized over <span class="math inline">\(\theta\)</span>; it does not depend on <span class="math inline">\(\theta\)</span>, so it plays no role in <em>shaping</em> the posterior, but it is usually the hardest single quantity in the whole framework to compute — it is a <span class="math inline">\(p\)</span>-dimensional integral with no generic closed form, and it is the running example of the next three chapters (numerical quadrature, Laplace approximation, and the Monte Carlo methods after that).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="cf">function</span>(t) <span class="fu">dnorm</span>(t, <span class="dv">3</span>, <span class="dv">1</span>); pri <span class="ot">&lt;-</span> <span class="cf">function</span>(t) <span class="fu">dnorm</span>(t, <span class="dv">2</span>, <span class="dv">4</span>) <span class="sc">*</span> <span class="fl">2.5</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(L, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">8</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(theta), <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">yaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">"prior and likelihood"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.45</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(pri, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"gray40"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"gray40"</span>, <span class="st">"firebrick"</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="fu">expression</span>(<span class="fu">pi</span>(theta)), <span class="fu">expression</span>(<span class="fu">L</span>(theta))))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="cf">function</span>(t) <span class="fu">L</span>(t) <span class="sc">*</span> <span class="fu">pri</span>(t); Z <span class="ot">&lt;-</span> <span class="fu">integrate</span>(post, <span class="sc">-</span><span class="dv">10</span>, <span class="dv">15</span>)<span class="sc">$</span>value</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="cf">function</span>(t) <span class="fu">post</span>(t) <span class="sc">/</span> Z</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(pd, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">8</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(theta), <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">yaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="fu">expression</span>(<span class="st">"posterior"</span> <span class="sc">%prop%</span> <span class="fu">L</span>(theta) <span class="sc">*</span> <span class="fu">pi</span>(theta)), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.45</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>tt <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">8</span>, <span class="at">length.out =</span> <span class="dv">1000</span>); cdf <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">pd</span>(tt)) <span class="sc">*</span> <span class="fu">diff</span>(tt)[<span class="dv">1</span>]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">c</span>(tt[<span class="fu">which.min</span>(<span class="fu">abs</span>(cdf <span class="sc">-</span> <span class="fl">0.025</span>))], tt[<span class="fu">which.min</span>(<span class="fu">abs</span>(cdf <span class="sc">-</span> <span class="fl">0.975</span>))])</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (side <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) { xs <span class="ot">&lt;-</span> <span class="cf">if</span> (side <span class="sc">==</span> <span class="dv">1</span>) <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>, q[<span class="dv">1</span>], <span class="at">length.out =</span> <span class="dv">100</span>) <span class="cf">else</span> <span class="fu">seq</span>(q[<span class="dv">2</span>], <span class="dv">8</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">polygon</span>(<span class="fu">c</span>(xs, <span class="fu">rev</span>(xs)), <span class="fu">c</span>(<span class="fu">pd</span>(xs), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">100</span>)), <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">"steelblue"</span>, <span class="fl">0.35</span>), <span class="at">border =</span> <span class="cn">NA</span>) }</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> q, <span class="at">lty =</span> <span class="dv">3</span>); <span class="fu">text</span>(q, <span class="fl">0.42</span>, <span class="fu">c</span>(<span class="fu">expression</span>(theta[alpha<span class="sc">/</span><span class="dv">2</span>]), <span class="fu">expression</span>(theta[<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>])))</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(q[<span class="dv">1</span>] <span class="sc">-</span> <span class="fl">0.5</span>, <span class="fl">0.05</span>, <span class="fu">expression</span>(alpha<span class="sc">/</span><span class="dv">2</span>)); <span class="fu">text</span>(q[<span class="dv">2</span>] <span class="sc">+</span> <span class="fl">0.5</span>, <span class="fl">0.05</span>, <span class="fu">expression</span>(alpha<span class="sc">/</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-prior-likelihood-posterior" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-prior-likelihood-posterior-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit07_bayesian_inference_files/figure-html/fig-prior-likelihood-posterior-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prior-likelihood-posterior-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Left: a flat-ish prior <span class="math inline">\(\pi(\theta)\)</span> (dashed) and a likelihood <span class="math inline">\(L(\theta)\)</span> (solid) that is much more concentrated — the data are far more informative than the prior here. Right: the posterior <span class="math inline">\(\propto L(\theta)\pi(\theta)\)</span>, essentially the (renormalized) likelihood since the prior is so flat over the region where <span class="math inline">\(L\)</span> has mass. Shaded tails cut off <span class="math inline">\(\alpha/2\)</span> of the posterior probability each, giving a <span class="math inline">\((1-\alpha)\)</span> credible interval <span class="math inline">\((\theta_{\alpha/2},\theta_{1-\alpha/2})\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="summarizing-the-posterior" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="summarizing-the-posterior"><span class="header-section-number">7.2</span> Summarizing the Posterior</h2>
<section id="point-estimates-from-loss-functions" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="point-estimates-from-loss-functions"><span class="header-section-number">7.2.1</span> Point estimates from loss functions</h3>
<p>A single number for <span class="math inline">\(\theta\)</span> is a decision, and a principled way to make a decision is to minimize expected loss. Given a loss function <span class="math inline">\(L(\theta,\hat\theta)\)</span> measuring the cost of reporting <span class="math inline">\(\hat\theta\)</span> when the truth is <span class="math inline">\(\theta\)</span>, the <strong>Bayes estimate</strong> minimizes the <em>posterior expected</em> loss, <span class="math display">\[
\hat\theta = \arg\min_{\hat\theta}\; E\big[L(\theta,\hat\theta)\mid y_{1:n}\big]
= \arg\min_{\hat\theta} \int L(\theta,\hat\theta)\,P(\theta\mid y_{1:n})\,d\theta.
\]</span> Three standard losses give three familiar summaries:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Loss <span class="math inline">\(L(\theta,\hat\theta)\)</span></th>
<th style="text-align: left;">Bayes estimate <span class="math inline">\(\hat\theta\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\((\theta-\hat\theta)^2\)</span> (squared error)</td>
<td style="text-align: left;">posterior mean <span class="math inline">\(E(\theta\mid y_{1:n})\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\lvert\theta-\hat\theta\rvert\)</span> (absolute error)</td>
<td style="text-align: left;">posterior median</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(I(\theta\ne\hat\theta)\)</span> (0–1 loss)</td>
<td style="text-align: left;">posterior mode (MAP)</td>
</tr>
</tbody>
</table>
<p><strong>Interval estimates</strong> go one step further: a <span class="math inline">\((1-\alpha)\)</span> <strong>credible interval</strong> <span class="math inline">\((\theta_{\alpha/2},\theta_{1-\alpha/2})\)</span> contains <span class="math inline">\(\theta\)</span> with posterior probability <span class="math inline">\(1-\alpha\)</span> — a direct probability statement about <span class="math inline">\(\theta\)</span> itself, unlike a frequentist confidence interval, whose <span class="math inline">\(1-\alpha\)</span> coverage is a statement about the <em>procedure</em> across repeated samples, not about <span class="math inline">\(\theta\)</span> given the data actually observed.</p>
<p>Every entry in that table is either an integral (a mean, a median, a probability) or an optimization (the mode) over the posterior. This is the sense in which Bayesian inference is inherently computational: even the most basic summaries require operations that, outside of conjugate models like the three worked below, have no closed form.</p>
</section>
<section id="posterior-prediction" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="posterior-prediction"><span class="header-section-number">7.2.2</span> Posterior prediction</h3>
<p>Often the real target is not <span class="math inline">\(\theta\)</span> itself but a future observation. The <strong>posterior predictive distribution</strong> of <span class="math inline">\(y_{n+1}\)</span> is <span class="math display">\[
P(y_{n+1}\mid y_{1:n}) = \frac{\int P(y_{n+1},y_{1:n}\mid\theta)\,\pi(\theta)\,d\theta}
{\int P(y_{1:n}\mid\theta)\,\pi(\theta)\,d\theta}.
\]</span> If <span class="math inline">\(y_1,\ldots,y_n,y_{n+1}\)</span> are conditionally independent given <span class="math inline">\(\theta\)</span> — the usual iid-sampling assumption — the joint density factors and this simplifies to <span class="math display">\[
P(y_{n+1}\mid y_{1:n}) = \int P(y_{n+1}\mid\theta)\,P(\theta\mid y_{1:n})\,d\theta,
\]</span> an <em>average</em> of the sampling density over the posterior, rather than the sampling density evaluated at one plug-in estimate <span class="math inline">\(\hat\theta\)</span>. Given posterior draws <span class="math inline">\(\theta_1,\ldots,\theta_J\sim P(\theta\mid y_{1:n})\)</span> (the subject of the Monte Carlo chapters later in the book), <span class="math display">\[
P(y_{n+1}\mid y_{1:n}) \approx \frac1J\sum_{j=1}^J P(y_{n+1}\mid\theta_j).
\]</span> Because it mixes over the whole posterior instead of conditioning on a single <span class="math inline">\(\hat\theta\)</span>, the predictive distribution is necessarily wider than any individual <span class="math inline">\(P(y_{n+1}\mid\theta_j)\)</span>: it carries both the sampling variability <em>and</em> the remaining uncertainty about <span class="math inline">\(\theta\)</span>. The Poisson–Gamma example below makes this concrete with a closed-form predictive distribution that is visibly overdispersed relative to a plug-in Poisson.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>)); J <span class="ot">&lt;-</span> <span class="dv">10</span>; th <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(J, <span class="dv">3</span>, <span class="fl">0.8</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, th[<span class="dv">1</span>]), <span class="sc">-</span><span class="dv">2</span>, <span class="dv">8</span>, <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">"firebrick"</span>, <span class="fl">0.6</span>), <span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.42</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="fu">expression</span>(y[n<span class="sc">+</span><span class="dv">1</span>]), <span class="at">ylab =</span> <span class="st">"density"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>J) <span class="fu">curve</span>(<span class="fu">dnorm</span>(x, th[j]), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">"firebrick"</span>, <span class="fl">0.6</span>), <span class="at">lwd =</span> <span class="fl">1.5</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">sapply</span>(x, <span class="cf">function</span>(v) <span class="fu">mean</span>(<span class="fu">dnorm</span>(v, th))), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">4</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">4</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"black"</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="fu">expression</span>(<span class="fu">P</span>(y[n<span class="sc">+</span><span class="dv">1</span>]<span class="sc">*</span><span class="st">"|"</span><span class="sc">*</span>theta[j])), <span class="fu">expression</span>(<span class="fu">P</span>(y[n<span class="sc">+</span><span class="dv">1</span>]<span class="sc">*</span><span class="st">"|"</span><span class="sc">*</span>y[<span class="dv">1</span><span class="sc">:</span>n]))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-predictive" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-predictive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit07_bayesian_inference_files/figure-html/fig-predictive-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-predictive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Red: the sampling density <span class="math inline">\(P(y_{n+1}\mid\theta_j)\)</span> for ten posterior draws <span class="math inline">\(\theta_j\sim N(3, 0.8^2)\)</span>. Black: their average, the posterior predictive density <span class="math inline">\(P(y_{n+1}\mid y_{1:n})\)</span>. The predictive is visibly wider than any single red curve — it inherits both the spread of <span class="math inline">\(P(y_{n+1}\mid\theta)\)</span> and the spread of the <span class="math inline">\(\theta_j\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="example-bernoulli-data-with-a-beta-prior" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="example-bernoulli-data-with-a-beta-prior"><span class="header-section-number">7.3</span> Example: Bernoulli Data with a Beta Prior</h2>
<section id="prior" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="prior"><span class="header-section-number">7.3.1</span> Prior</h3>
<p>Let <span class="math inline">\(y_1,\ldots,y_n\mid\theta \overset{iid}{\sim}\text{Bern}(\theta)\)</span>, with <span class="math inline">\(\theta\in(0,1)\)</span> a success probability, and give <span class="math inline">\(\theta\)</span> a <span class="math inline">\(\text{Beta}(\alpha_1,\alpha_0)\)</span> prior, <span class="math inline">\(\alpha_1,\alpha_0&gt;0\)</span> given: <span class="math display">\[
\pi(\theta) = \frac{\Gamma(\alpha_0+\alpha_1)}{\Gamma(\alpha_0)\Gamma(\alpha_1)}\,
\theta^{\alpha_1-1}(1-\theta)^{\alpha_0-1}, \qquad 0&lt;\theta&lt;1,
\]</span> <span class="math display">\[
E(\theta) = \frac{\alpha_1}{\alpha_0+\alpha_1}, \qquad
V(\theta) = \frac{\alpha_0\alpha_1}{(\alpha_0+\alpha_1)^2(\alpha_0+\alpha_1+1)}.
\]</span> The parameters have a direct reading as <em>pseudo-data</em>: <span class="math inline">\(\alpha_1\)</span> behaves like a prior count of successes, <span class="math inline">\(\alpha_0\)</span> a prior count of failures, and <span class="math inline">\(\alpha_0+\alpha_1\)</span> a prior “sample size” — the more of it, the more concentrated <span class="math inline">\(\pi(\theta)\)</span> is around <span class="math inline">\(\alpha_1/(\alpha_0+\alpha_1)\)</span>, exactly as a real sample of that size would concentrate a Bernoulli proportion. <span class="math inline">\(\text{Beta}(1,1)\)</span> is <span class="math inline">\(\text{Unif}(0,1)\)</span>, a genuinely flat prior; small <span class="math inline">\(\alpha\)</span>’s (e.g.&nbsp;<span class="math inline">\(\text{Beta}(0.5,0.5)\)</span>) give a U-shaped prior that expects <span class="math inline">\(\theta\)</span> near <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span>; large, unequal <span class="math inline">\(\alpha\)</span>’s concentrate the prior away from <span class="math inline">\(\tfrac12\)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pars <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>), <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>), <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">10</span>), <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">10</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"firebrick"</span>, <span class="st">"darkorange"</span>, <span class="st">"forestgreen"</span>, <span class="st">"steelblue"</span>, <span class="st">"purple"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">6</span>), <span class="at">xlab =</span> <span class="fu">expression</span>(theta), <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">pi</span>(theta)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">seq_along</span>(pars)) <span class="fu">curve</span>(<span class="fu">dbeta</span>(x, pars[[k]][<span class="dv">1</span>], pars[[k]][<span class="dv">2</span>]), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> cols[k], <span class="at">n =</span> <span class="dv">501</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"top"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> cols, <span class="at">ncol =</span> <span class="dv">3</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">sapply</span>(pars, <span class="cf">function</span>(p) <span class="fu">sprintf</span>(<span class="st">"Beta(%g, %g)"</span>, p[<span class="dv">1</span>], p[<span class="dv">2</span>])))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-beta-priors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-beta-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit07_bayesian_inference_files/figure-html/fig-beta-priors-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-beta-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.3: Six Beta priors spanning flat, U-shaped, and concentrated shapes. Beta(1,1) is uniform; Beta(0.5,0.5) is U-shaped, favouring <span class="math inline">\(\theta\)</span> near the boundaries; Beta(2,5) and Beta(30,10) are increasingly concentrated, at <span class="math inline">\(\theta\approx2/7\)</span> and <span class="math inline">\(\theta\approx0.75\)</span> respectively.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="likelihood-and-posterior" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="likelihood-and-posterior"><span class="header-section-number">7.3.2</span> Likelihood and posterior</h3>
<p>With <span class="math inline">\(P(y_i\mid\theta) = \theta^{y_i}(1-\theta)^{1-y_i}\)</span> and <span class="math inline">\(\mathbf y = (y_1,\ldots,y_n)\)</span>, the likelihood depends on the data only through the total number of successes: <span class="math display">\[
L(\theta) = \prod_{i=1}^n \theta^{y_i}(1-\theta)^{1-y_i} = \theta^{n_1}(1-\theta)^{n_0},
\qquad n_1 = \sum_i y_i,\ \ n_0 = n - n_1.
\]</span> Multiplying by the prior and collecting powers of <span class="math inline">\(\theta\)</span> and <span class="math inline">\(1-\theta\)</span>, <span class="math display">\[
f(\theta) = \pi(\theta)L(\theta) \;\propto\; \theta^{\alpha_1-1}(1-\theta)^{\alpha_0-1}\cdot\theta^{n_1}(1-\theta)^{n_0}
= \theta^{(\alpha_1+n_1)-1}(1-\theta)^{(\alpha_0+n_0)-1}.
\]</span> This unnormalized posterior is, up to the constant <span class="math inline">\(P(\mathbf y)\)</span>, exactly the Beta kernel with updated parameters <span class="math inline">\(\alpha_1' = \alpha_1+n_1\)</span>, <span class="math inline">\(\alpha_0' = \alpha_0+n_0\)</span> — and since a Beta density is the <em>only</em> normalized distribution with that kernel, <span class="math display">\[
\theta\mid\mathbf y \sim \text{Beta}(\alpha_1+n_1,\ \alpha_0+n_0)
\]</span> follows immediately, with no integration needed. This is what it means for the Beta prior to be <strong>conjugate</strong> to the Bernoulli likelihood: updating the prior to the posterior is nothing but arithmetic on the two parameters, <span class="math inline">\(\alpha_1 \to \alpha_1+n_1\)</span>, <span class="math inline">\(\alpha_0\to\alpha_0+n_0\)</span>, and the marginal likelihood <span class="math inline">\(P(\mathbf y)\)</span> never has to be computed explicitly, because matching the two Beta kernels pins down the normalizing constant for free. Few models have this property; it is a stroke of algebraic luck rather than a general feature of Bayesian inference, which is exactly why the rest of this book is needed.</p>
</section>
<section id="posterior-summaries" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="posterior-summaries"><span class="header-section-number">7.3.3</span> Posterior summaries</h3>
<p>The pseudo-data reading of <span class="math inline">\(\alpha_1,\alpha_0\)</span> carries through to the posterior mean, which is an exact weighted average of the prior mean and the MLE <span class="math inline">\(\hat\theta_{\text{MLE}} = n_1/n\)</span>: <span class="math display">\[
E(\theta\mid\mathbf y) = \frac{\alpha_1+n_1}{\alpha_0+\alpha_1+n}
= \underbrace{\frac{\alpha_0+\alpha_1}{\alpha_0+\alpha_1+n}}_{w}\cdot\frac{\alpha_1}{\alpha_0+\alpha_1}
+ (1-w)\cdot\hat\theta_{\text{MLE}}.
\]</span> The weight <span class="math inline">\(w\)</span> on the prior mean is the prior’s pseudo-sample-size relative to the total (prior plus real) sample size; as <span class="math inline">\(n\to\infty\)</span>, <span class="math inline">\(w\to0\)</span> and the posterior mean converges to the MLE regardless of the prior. The posterior variance, <span class="math display">\[
V(\theta\mid\mathbf y) = \frac{(\alpha_1+n_1)(\alpha_0+n_0)}{(n+\alpha_0+\alpha_1)^2(n+\alpha_0+\alpha_1+1)} = O\!\left(\frac1n\right),
\]</span> shrinks at the same <span class="math inline">\(1/n\)</span> rate as the sampling variance of the MLE, <span class="math inline">\(\hat\theta_{\text{MLE}}\,\dot\sim\,N\big(\theta_0,\,1/(nI(\theta_0))\big)\)</span> from the MLE chapters — for large <span class="math inline">\(n\)</span> the two approaches to uncertainty agree, with the prior’s influence vanishing.</p>
</section>
<section id="the-marginal-likelihood-in-closed-form" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="the-marginal-likelihood-in-closed-form"><span class="header-section-number">7.3.4</span> The marginal likelihood in closed form</h3>
<p>Because conjugacy gives the <em>whole</em> posterior in closed form, it also gives the marginal likelihood <span class="math inline">\(P(\mathbf y)=\int_0^1 f(\theta)\,d\theta\)</span> in closed form, by integrating the unnormalized Beta kernel directly against its own normalizing constant: <span class="math display">\[
P(\mathbf y) = \frac{\Gamma(\alpha_0+\alpha_1)}{\Gamma(\alpha_0)\Gamma(\alpha_1)}
\int_0^1 \theta^{(\alpha_1+n_1)-1}(1-\theta)^{(\alpha_0+n_0)-1}\,d\theta
= \frac{\Gamma(\alpha_0+\alpha_1)}{\Gamma(\alpha_0)\Gamma(\alpha_1)}\cdot
\frac{\Gamma(\alpha_1+n_1)\,\Gamma(\alpha_0+n_0)}{\Gamma(\alpha_0+\alpha_1+n)},
\]</span> using <span class="math inline">\(\int_0^1\theta^{a-1}(1-\theta)^{b-1}\,d\theta = B(a,b) =
\Gamma(a)\Gamma(b)/\Gamma(a+b)\)</span>. On the log scale, with <span class="math inline">\(\log B(a,b)=\log\Gamma(a)+\log\Gamma(b)-\log\Gamma(a+b)\)</span>, <span class="math display">\[
\log P(\mathbf y) = \log B(\alpha_1+n_1,\ \alpha_0+n_0) - \log B(\alpha_1,\ \alpha_0).
\]</span> This exact Beta–Bernoulli conjugate identity is the same trick used for Gamma–Poisson and Normal–Normal below: matching a recognizable kernel against its own normalizing constant hands over <span class="math inline">\(P(\mathbf y)\)</span> for free, with no numerical integration anywhere.</p>
</section>
<section id="posterior-predictive-in-closed-form" class="level3" data-number="7.3.5">
<h3 data-number="7.3.5" class="anchored" data-anchor-id="posterior-predictive-in-closed-form"><span class="header-section-number">7.3.5</span> Posterior predictive, in closed form</h3>
<p>For a new <span class="math inline">\(y_{n+1}\mid\theta\sim\text{Bern}(\theta)\)</span>, the general predictive formula from earlier in this chapter simplifies beautifully in the conjugate case, because <span class="math inline">\(E(\theta\mid\mathbf y)\)</span> <em>is</em> the predictive success probability: <span class="math display">\[
P(y_{n+1}=1\mid\mathbf y) = \int_0^1 \theta\, P(\theta\mid\mathbf y)\,d\theta = E(\theta\mid\mathbf y),
\qquad y_{n+1}\mid\mathbf y \sim \text{Bern}\big(E(\theta\mid\mathbf y)\big).
\]</span> This exact equality (<span class="math inline">\(E(\theta\mid\mathbf y)\)</span> doing double duty as both a point estimate of <span class="math inline">\(\theta\)</span> and the predictive probability of success) is special to Bernoulli data; the Poisson–Gamma and Normal–Normal examples below give predictive distributions that are genuinely wider than their plug-in sampling models.</p>
</section>
<section id="worked-numbers-the-complete-inference-output" class="level3" data-number="7.3.6">
<h3 data-number="7.3.6" class="anchored" data-anchor-id="worked-numbers-the-complete-inference-output"><span class="header-section-number">7.3.6</span> Worked numbers: the complete inference output</h3>
<p>Take a near-flat <span class="math inline">\(\text{Beta}(1,1)\)</span> prior and <span class="math inline">\(n=10\)</span> trials with <span class="math inline">\(y=7\)</span> successes. The table below collects everything derived above — marginal likelihood, posterior, its mean/sd and credible interval, and the predictive distribution — in one place, and the same five quantities are computed the same way for the Gamma–Poisson and Normal–Normal examples that follow:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="dv">1</span>; a0 <span class="ot">&lt;-</span> <span class="dv">1</span>                 <span class="co"># Beta(1, 1): uniform prior</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>n_bb <span class="ot">&lt;-</span> <span class="dv">10</span>; y_bb <span class="ot">&lt;-</span> <span class="dv">7</span>            <span class="co"># 7 successes out of 10 trials</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>post_a1 <span class="ot">&lt;-</span> a1 <span class="sc">+</span> y_bb; post_a0 <span class="ot">&lt;-</span> a0 <span class="sc">+</span> (n_bb <span class="sc">-</span> y_bb)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>bb_logmarg <span class="ot">&lt;-</span> <span class="fu">lbeta</span>(post_a1, post_a0) <span class="sc">-</span> <span class="fu">lbeta</span>(a1, a0)   <span class="co"># log P(y), exact</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>bb_mean <span class="ot">&lt;-</span> post_a1 <span class="sc">/</span> (post_a1 <span class="sc">+</span> post_a0)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>bb_sd   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(post_a1 <span class="sc">*</span> post_a0 <span class="sc">/</span> ((post_a1 <span class="sc">+</span> post_a0)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (post_a1 <span class="sc">+</span> post_a0 <span class="sc">+</span> <span class="dv">1</span>)))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>bb_ci   <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), post_a1, post_a0)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>bb_pred_mean <span class="ot">&lt;-</span> bb_mean                        <span class="co"># predictive: Bernoulli(bb_mean)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>bb_pred_sd   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(bb_pred_mean <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> bb_pred_mean))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">quantity =</span> <span class="fu">c</span>(<span class="st">"prior mean"</span>, <span class="st">"MLE ($y/n$)"</span>, <span class="st">"log marginal likelihood"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"posterior distribution"</span>, <span class="st">"posterior mean"</span>, <span class="st">"posterior sd"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"95% credible interval"</span>, <span class="st">"predictive distribution"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"predictive mean"</span>, <span class="st">"predictive sd"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, a1 <span class="sc">/</span> (a1 <span class="sc">+</span> a0)), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, y_bb <span class="sc">/</span> n_bb),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, bb_logmarg),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"Beta(%d, %d)"</span>, post_a1, post_a0),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, bb_mean), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, bb_sd),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"(%.3f, %.3f)"</span>, bb_ci[<span class="dv">1</span>], bb_ci[<span class="dv">2</span>]),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"Bernoulli(%.3f)"</span>, bb_pred_mean),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, bb_pred_mean), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, bb_pred_sd))</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>), <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"quantity"</span>, <span class="st">"value"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-bb-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bb-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: Complete inference output, Beta(1,1) prior with n = 10, y = 7.
</figcaption>
<div aria-describedby="tbl-bb-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">quantity</th>
<th style="text-align: left;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">prior mean</td>
<td style="text-align: left;">0.500</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLE (<span class="math inline">\(y/n\)</span>)</td>
<td style="text-align: left;">0.700</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log marginal likelihood</td>
<td style="text-align: left;">-7.185</td>
</tr>
<tr class="even">
<td style="text-align: left;">posterior distribution</td>
<td style="text-align: left;">Beta(8, 4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">posterior mean</td>
<td style="text-align: left;">0.667</td>
</tr>
<tr class="even">
<td style="text-align: left;">posterior sd</td>
<td style="text-align: left;">0.131</td>
</tr>
<tr class="odd">
<td style="text-align: left;">95% credible interval</td>
<td style="text-align: left;">(0.390, 0.891)</td>
</tr>
<tr class="even">
<td style="text-align: left;">predictive distribution</td>
<td style="text-align: left;">Bernoulli(0.667)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">predictive mean</td>
<td style="text-align: left;">0.667</td>
</tr>
<tr class="even">
<td style="text-align: left;">predictive sd</td>
<td style="text-align: left;">0.471</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>With a uniform prior the posterior mean <span class="math inline">\(0.667\)</span> sits between the prior mean <span class="math inline">\(0.5\)</span> and the MLE <span class="math inline">\(0.7\)</span>, pulled almost all the way to the MLE because the prior carries only <span class="math inline">\(\alpha_0+\alpha_1=2\)</span> pseudo-observations against <span class="math inline">\(10\)</span> real ones. The 95% credible interval, <span class="math inline">\((0.390, 0.891)\)</span>, is read directly off the Beta CDF (<code>qbeta</code>) — no simulation, no quadrature, because conjugacy already handed over the exact posterior family. The predictive distribution <span class="math inline">\(\text{Bern}(0.667)\)</span> has the same mean as the posterior but a nonzero sd (<span class="math inline">\(0.471\)</span>), because even a Bernoulli outcome is uncertain even once <span class="math inline">\(\theta\)</span> is known exactly.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>)); a1p <span class="ot">&lt;-</span> <span class="dv">2</span>; a0p <span class="ot">&lt;-</span> <span class="dv">2</span>; ybar <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">200</span>); cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"darkorange"</span>, <span class="st">"steelblue"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">13</span>), <span class="at">xlab =</span> <span class="fu">expression</span>(theta), <span class="at">ylab =</span> <span class="st">"density"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dbeta</span>(x, a1p, a0p), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray40"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">seq_along</span>(ns)) <span class="fu">curve</span>(<span class="fu">dbeta</span>(x, a1p <span class="sc">+</span> ns[k] <span class="sc">*</span> ybar, a0p <span class="sc">+</span> ns[k] <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> ybar)), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> cols[k])</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ybar, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"gray40"</span>, cols),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"prior Beta(2, 2)"</span>, <span class="fu">paste0</span>(<span class="st">"posterior, n = "</span>, ns)))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(ybar, <span class="fl">12.5</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(theta)[MLE]), <span class="at">pos =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-beta-posterior-narrowing" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-beta-posterior-narrowing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit07_bayesian_inference_files/figure-html/fig-beta-posterior-narrowing-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-beta-posterior-narrowing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.4: Prior Beta(2,2) (dashed) and posteriors after <span class="math inline">\(n=10,50,200\)</span> observations with <span class="math inline">\(\bar y=0.7\)</span> held fixed. The posterior narrows at rate <span class="math inline">\(1/\sqrt n\)</span> and moves onto the MLE as <span class="math inline">\(n\)</span> grows, exactly the <span class="math inline">\(w\to0\)</span> argument above made visible.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="example-poisson-data-with-a-gamma-prior" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="example-poisson-data-with-a-gamma-prior"><span class="header-section-number">7.4</span> Example: Poisson Data with a Gamma Prior</h2>
<section id="prior-1" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="prior-1"><span class="header-section-number">7.4.1</span> Prior</h3>
<p>Now let <span class="math inline">\(y_1,\ldots,y_n\mid\lambda \overset{iid}{\sim}\text{Poisson}(\lambda)\)</span>, <span class="math inline">\(\lambda&gt;0\)</span> a rate, with a <span class="math inline">\(\text{Gamma}(\alpha,\beta)\)</span> prior (shape <span class="math inline">\(\alpha\)</span>, rate <span class="math inline">\(\beta\)</span>), <span class="math display">\[
\pi(\lambda) = \frac{\beta^\alpha}{\Gamma(\alpha)}\lambda^{\alpha-1}e^{-\beta\lambda}, \qquad \lambda&gt;0,
\qquad E(\lambda) = \frac{\alpha}{\beta}, \qquad V(\lambda) = \frac{\alpha}{\beta^2}.
\]</span> The pseudo-data reading again applies, with the two parameters playing different roles than in the Beta case: <span class="math inline">\(\alpha\)</span> behaves like a prior total count and <span class="math inline">\(\beta\)</span> like a prior total <em>exposure</em> (a number of pseudo time-units or pseudo-observations already seen with rate <span class="math inline">\(\lambda\)</span>), so <span class="math inline">\(\alpha/\beta\)</span> is a prior average rate — the same “counts per exposure” structure as <span class="math inline">\(\hat\lambda_{\text{MLE}} = \sum y_i / n\)</span>, with <span class="math inline">\(\beta\)</span> playing the role <span class="math inline">\(n\)</span> plays in the likelihood.</p>
</section>
<section id="likelihood-and-posterior-1" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="likelihood-and-posterior-1"><span class="header-section-number">7.4.2</span> Likelihood and posterior</h3>
<p>With <span class="math inline">\(P(y_i\mid\lambda) = \lambda^{y_i}e^{-\lambda}/y_i!\)</span>, the likelihood depends on the data only through the total count <span class="math inline">\(S=\sum_i y_i\)</span>: <span class="math display">\[
L(\lambda) = \prod_{i=1}^n \frac{\lambda^{y_i}e^{-\lambda}}{y_i!}
= \frac{\lambda^{S}e^{-n\lambda}}{\prod_i y_i!}, \qquad S = \sum_{i=1}^n y_i.
\]</span> Multiplying by the prior and collecting powers of <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(e^{-\lambda}\)</span>, <span class="math display">\[
f(\lambda) = \pi(\lambda)L(\lambda) \;\propto\; \lambda^{\alpha-1}e^{-\beta\lambda}\cdot\lambda^{S}e^{-n\lambda}
= \lambda^{(\alpha+S)-1}e^{-(\beta+n)\lambda},
\]</span> the kernel of a <span class="math inline">\(\text{Gamma}(\alpha+S,\ \beta+n)\)</span> density. The Gamma prior is therefore <strong>conjugate</strong> to the Poisson likelihood, exactly as Beta was to Bernoulli, and by the same argument (matching a recognizable kernel pins down the normalizing constant automatically): <span class="math display">\[
\lambda\mid\mathbf y \sim \text{Gamma}(\alpha+S,\ \beta+n).
\]</span> The posterior mean has precisely the weighted-average structure seen in the Bernoulli case, with <span class="math inline">\(\beta\)</span> now playing the role <span class="math inline">\(\alpha_0+\alpha_1\)</span> played there: <span class="math display">\[
E(\lambda\mid\mathbf y) = \frac{\alpha+S}{\beta+n}
= \underbrace{\frac{\beta}{\beta+n}}_{w}\cdot\frac{\alpha}{\beta}
+ (1-w)\cdot\underbrace{\frac{S}{n}}_{\hat\lambda_{\text{MLE}}},
\]</span> a weighted average of the prior mean and the MLE, with prior weight <span class="math inline">\(w=\beta/(\beta+n)\to0\)</span> as <span class="math inline">\(n\to\infty\)</span> — the same shrinkage story as Beta–Bernoulli, now driven by <span class="math inline">\(\beta\)</span> (prior pseudo-exposure) instead of <span class="math inline">\(\alpha_0+\alpha_1\)</span> (prior pseudo-sample-size).</p>
</section>
<section id="the-marginal-likelihood-in-closed-form-1" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="the-marginal-likelihood-in-closed-form-1"><span class="header-section-number">7.4.3</span> The marginal likelihood in closed form</h3>
<p>Because conjugacy gives the <em>whole</em> posterior in closed form, it also gives the marginal likelihood <span class="math inline">\(P(\mathbf y)=\int f(\lambda)\,d\lambda\)</span> in closed form, by integrating the unnormalized Gamma kernel directly against its own normalizing constant: <span class="math display">\[
P(\mathbf y) = \left(\prod_{i=1}^n \frac1{y_i!}\right)\frac{\beta^\alpha}{\Gamma(\alpha)}
\int_0^\infty \lambda^{(\alpha+S)-1}e^{-(\beta+n)\lambda}\,d\lambda
= \left(\prod_{i=1}^n \frac1{y_i!}\right)\frac{\beta^\alpha\,\Gamma(\alpha+S)}{\Gamma(\alpha)\,(\beta+n)^{\alpha+S}},
\]</span> using <span class="math inline">\(\int_0^\infty \lambda^{k-1}e^{-c\lambda}\,d\lambda = \Gamma(k)/c^k\)</span>. On the log scale, <span class="math display">\[
\log P(\mathbf y) = \alpha\log\beta - \log\Gamma(\alpha) + \log\Gamma(\alpha+S)
- (\alpha+S)\log(\beta+n) - \sum_{i=1}^n \log(y_i!).
\]</span> This exact Gamma–Poisson conjugate identity is what makes the Poisson-rate model a useful <em>test case</em> for approximate methods: the Laplace approximation chapter later in this book applies its mode-and-curvature approximation to this same model and checks the result against precisely this formula, since here — unlike in most applications — the truth is known.</p>
</section>
<section id="posterior-predictive-in-closed-form-1" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="posterior-predictive-in-closed-form-1"><span class="header-section-number">7.4.4</span> Posterior predictive, in closed form</h3>
<p>For a new count <span class="math inline">\(y_{n+1}\mid\lambda\sim\text{Poisson}(\lambda)\)</span>, integrating the Poisson sampling density against the <span class="math inline">\(\text{Gamma}(\alpha+S,\beta+n)\)</span> posterior gives a <strong>Negative Binomial</strong> predictive distribution, <span class="math display">\[
P(y_{n+1}\mid\mathbf y) = \int_0^\infty \frac{\lambda^{y_{n+1}}e^{-\lambda}}{y_{n+1}!}\,
\frac{(\beta+n)^{\alpha+S}}{\Gamma(\alpha+S)}\lambda^{(\alpha+S)-1}e^{-(\beta+n)\lambda}\,d\lambda
= \text{NegBin}\!\left(\text{size}=\alpha+S,\ \ p=\frac{\beta+n}{\beta+n+1}\right),
\]</span> by the same Gamma-integral identity used for the marginal likelihood above. Its mean matches the posterior mean of <span class="math inline">\(\lambda\)</span> exactly (as it must, by the tower property), but its variance is <em>larger</em> than that of a plug-in Poisson at the posterior mean rate: <span class="math display">\[
E(y_{n+1}\mid\mathbf y) = \frac{\alpha+S}{\beta+n}, \qquad
V(y_{n+1}\mid\mathbf y) = \frac{\alpha+S}{\beta+n}\left(1+\frac1{\beta+n}\right)
= E(y_{n+1}\mid\mathbf y)\cdot\Big(1+\tfrac{1}{\beta+n}\Big).
\]</span> A plug-in Poisson at <span class="math inline">\(\lambda=E(\lambda\mid\mathbf y)\)</span> would have variance <em>equal</em> to its mean — the extra factor <span class="math inline">\(1+1/(\beta+n)\)</span> is entirely the posterior uncertainty about <span class="math inline">\(\lambda\)</span> leaking into the prediction, exactly the “wider than any single <span class="math inline">\(P(y_{n+1}\mid\theta_j)\)</span>” phenomenon from the general framework above, now with an explicit formula for <em>how much</em> wider.</p>
</section>
<section id="worked-numbers-the-complete-inference-output-1" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="worked-numbers-the-complete-inference-output-1"><span class="header-section-number">7.4.5</span> Worked numbers: the complete inference output</h3>
<p>Take <span class="math inline">\(\text{Gamma}(2,1)\)</span> as the prior (prior mean <span class="math inline">\(2\)</span>, i.e.&nbsp;a mild belief that the rate is around <span class="math inline">\(2\)</span>, with pseudo-exposure <span class="math inline">\(\beta=1\)</span>) and <span class="math inline">\(n=8\)</span> simulated counts from a true rate of <span class="math inline">\(3\)</span>. The table collects the same five quantities as the Beta–Bernoulli table above — marginal likelihood, posterior, its mean/sd and credible interval, and the predictive distribution:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="dv">2</span>; beta <span class="ot">&lt;-</span> <span class="dv">1</span>                       <span class="co"># Gamma(2, 1) prior</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>n_pg <span class="ot">&lt;-</span> <span class="dv">8</span>; y_pg <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n_pg, <span class="dv">3</span>)           <span class="co"># 8 counts from a true rate of 3</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>S_pg <span class="ot">&lt;-</span> <span class="fu">sum</span>(y_pg)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>post_alpha <span class="ot">&lt;-</span> alpha <span class="sc">+</span> S_pg; post_beta <span class="ot">&lt;-</span> beta <span class="sc">+</span> n_pg</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>pg_logmarg <span class="ot">&lt;-</span> alpha <span class="sc">*</span> <span class="fu">log</span>(beta) <span class="sc">-</span> <span class="fu">lgamma</span>(alpha) <span class="sc">+</span> <span class="fu">lgamma</span>(post_alpha) <span class="sc">-</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  post_alpha <span class="sc">*</span> <span class="fu">log</span>(post_beta) <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(y_pg <span class="sc">+</span> <span class="dv">1</span>))     <span class="co"># log P(y), exact</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>pg_mean <span class="ot">&lt;-</span> post_alpha <span class="sc">/</span> post_beta</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>pg_sd   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(post_alpha) <span class="sc">/</span> post_beta</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>pg_ci   <span class="ot">&lt;-</span> <span class="fu">qgamma</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), post_alpha, post_beta)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>pg_nb_prob   <span class="ot">&lt;-</span> post_beta <span class="sc">/</span> (post_beta <span class="sc">+</span> <span class="dv">1</span>)    <span class="co"># predictive: NegBin(post_alpha, pg_nb_prob)</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>pg_pred_mean <span class="ot">&lt;-</span> pg_mean</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>pg_pred_sd   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(pg_mean <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> post_beta))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">quantity =</span> <span class="fu">c</span>(<span class="st">"data $y_{1:8}$"</span>, <span class="st">"sum $S$"</span>, <span class="st">"prior mean"</span>, <span class="st">"MLE ($S/n$)"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"log marginal likelihood"</span>, <span class="st">"posterior distribution"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"posterior mean"</span>, <span class="st">"posterior sd"</span>, <span class="st">"95% credible interval"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"predictive distribution"</span>, <span class="st">"predictive mean"</span>, <span class="st">"predictive sd"</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="fu">paste</span>(y_pg, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="fu">as.character</span>(S_pg),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, alpha <span class="sc">/</span> beta), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, S_pg <span class="sc">/</span> n_pg),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, pg_logmarg),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"Gamma(%d, %d)"</span>, post_alpha, post_beta),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, pg_mean), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, pg_sd),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"(%.3f, %.3f)"</span>, pg_ci[<span class="dv">1</span>], pg_ci[<span class="dv">2</span>]),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"NegBin(%d, %.3f)"</span>, post_alpha, pg_nb_prob),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, pg_pred_mean), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, pg_pred_sd))</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>), <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"quantity"</span>, <span class="st">"value"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-pg-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pg-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.2: Complete inference output, Gamma(2,1) prior, n = 8 Poisson counts.
</figcaption>
<div aria-describedby="tbl-pg-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">quantity</th>
<th style="text-align: left;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">data <span class="math inline">\(y_{1:8}\)</span></td>
<td style="text-align: left;">5, 6, 2, 5, 3, 3, 4, 1</td>
</tr>
<tr class="even">
<td style="text-align: left;">sum <span class="math inline">\(S\)</span></td>
<td style="text-align: left;">29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prior mean</td>
<td style="text-align: left;">2.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLE (<span class="math inline">\(S/n\)</span>)</td>
<td style="text-align: left;">3.625</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log marginal likelihood</td>
<td style="text-align: left;">-17.065</td>
</tr>
<tr class="even">
<td style="text-align: left;">posterior distribution</td>
<td style="text-align: left;">Gamma(31, 9)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">posterior mean</td>
<td style="text-align: left;">3.444</td>
</tr>
<tr class="even">
<td style="text-align: left;">posterior sd</td>
<td style="text-align: left;">0.619</td>
</tr>
<tr class="odd">
<td style="text-align: left;">95% credible interval</td>
<td style="text-align: left;">(2.340, 4.759)</td>
</tr>
<tr class="even">
<td style="text-align: left;">predictive distribution</td>
<td style="text-align: left;">NegBin(31, 0.900)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">predictive mean</td>
<td style="text-align: left;">3.444</td>
</tr>
<tr class="even">
<td style="text-align: left;">predictive sd</td>
<td style="text-align: left;">1.956</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The MLE, <span class="math inline">\(29/8=3.625\)</span>, and the prior mean, <span class="math inline">\(2\)</span>, are pulled toward each other by the posterior mean <span class="math inline">\(3.444\)</span> — mostly toward the MLE, since the prior’s pseudo-exposure <span class="math inline">\(\beta=1\)</span> is small next to the real <span class="math inline">\(n=8\)</span>. Compare this to the true generating rate of <span class="math inline">\(3\)</span>: both the MLE and the posterior mean overshoot it here (this particular simulated sample happened to run a bit high), and the 95% credible interval <span class="math inline">\((2.340, 4.759)\)</span> still comfortably covers it. With <span class="math inline">\(\beta+n=9\)</span>, the predictive sd <span class="math inline">\(1.957\)</span> exceeds the plug-in Poisson sd <span class="math inline">\(\sqrt{3.444}=1.856\)</span> by the factor <span class="math inline">\(\sqrt{1+1/9}\)</span> — the same overdispersion story made numeric.</p>
</section>
<section id="overdispersion-visualized" class="level3" data-number="7.4.6">
<h3 data-number="7.4.6" class="anchored" data-anchor-id="overdispersion-visualized"><span class="header-section-number">7.4.6</span> Overdispersion, visualized</h3>
<p>The gap is small here because <span class="math inline">\(n\)</span> is already large relative to the prior, but it widens as <span class="math inline">\(n\)</span> shrinks or the prior gets vaguer (smaller <span class="math inline">\(\beta\)</span>). The figure below makes the same point on the density scale: the predictive has visibly heavier tails than a plug-in Poisson with the same mean.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">12</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>nb_prob <span class="ot">&lt;-</span> post_beta <span class="sc">/</span> (post_beta <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>pred_nb     <span class="ot">&lt;-</span> <span class="fu">dnbinom</span>(ks, <span class="at">size =</span> post_alpha, <span class="at">prob =</span> nb_prob)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>pred_plugin <span class="ot">&lt;-</span> <span class="fu">dpois</span>(ks, pg_mean)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">rbind</span>(pred_nb, pred_plugin), <span class="at">beside =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"gray60"</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">names.arg =</span> ks, <span class="at">xlab =</span> <span class="fu">expression</span>(y[n<span class="sc">+</span><span class="dv">1</span>]), <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">P</span>(y[n<span class="sc">+</span><span class="dv">1</span>])))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"gray60"</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"posterior predictive (Negative Binomial)"</span>, <span class="st">"plug-in Poisson at posterior mean"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-pg-predictive-dispersion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pg-predictive-dispersion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit07_bayesian_inference_files/figure-html/fig-pg-predictive-dispersion-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pg-predictive-dispersion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.5: Posterior predictive <span class="math inline">\(P(y_{n+1}\mid\mathbf y)\)</span> (Negative Binomial, red) against a plug-in Poisson at the posterior mean rate (gray). Same mean, but the predictive has heavier tails: the two bars noticeably diverge above <span class="math inline">\(y_{n+1}=7\)</span>, and <span class="math inline">\(V(y_{n+1}\mid\mathbf y)\)</span> exceeds the plug-in variance by the factor <span class="math inline">\(1+1/(\beta+n)=1.111\)</span> derived above.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="example-normal-data-with-a-normal-prior-known-variance" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="example-normal-data-with-a-normal-prior-known-variance"><span class="header-section-number">7.5</span> Example: Normal Data with a Normal Prior (Known Variance)</h2>
<section id="prior-2" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="prior-2"><span class="header-section-number">7.5.1</span> Prior</h3>
<p>Now let <span class="math inline">\(y_1,\ldots,y_n\mid\mu \overset{iid}{\sim} N(\mu,\sigma^2)\)</span>, with <span class="math inline">\(\sigma^2\)</span> <strong>known/fixed</strong> and only the mean <span class="math inline">\(\mu\in\mathbb R\)</span> unknown. Give <span class="math inline">\(\mu\)</span> a Normal prior, parametrized through a prior pseudo-sample-size <span class="math inline">\(\kappa_0&gt;0\)</span> so that it lines up with the pseudo-data reading used in the two examples above: <span class="math display">\[
\pi(\mu) = N\!\Big(\mu_0,\ \frac{\sigma^2}{\kappa_0}\Big), \qquad
E(\mu) = \mu_0, \qquad V(\mu) = \frac{\sigma^2}{\kappa_0}.
\]</span> <span class="math inline">\(\mu_0\)</span> is the prior guess for <span class="math inline">\(\mu\)</span>, and <span class="math inline">\(\kappa_0\)</span> counts how many pseudo-observations (each with the known variance <span class="math inline">\(\sigma^2\)</span>) that guess is worth: large <span class="math inline">\(\kappa_0\)</span> means a confident, concentrated prior; <span class="math inline">\(\kappa_0\to0\)</span> recovers a flat, uninformative prior on <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="likelihood-and-posterior-2" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="likelihood-and-posterior-2"><span class="header-section-number">7.5.2</span> Likelihood and posterior</h3>
<p>With <span class="math inline">\(P(y_i\mid\mu) = (2\pi\sigma^2)^{-1/2}\exp\{-(y_i-\mu)^2/(2\sigma^2)\}\)</span>, the likelihood depends on the data only through the sample mean <span class="math inline">\(\bar y = \frac1n\sum_i y_i\)</span>: <span class="math display">\[
L(\mu) \;\propto\; \exp\left\{-\frac1{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2\right\}
\;\propto\; \exp\left\{-\frac{n(\mu-\bar y)^2}{2\sigma^2}\right\}.
\]</span> Multiplying by the prior and completing the square in <span class="math inline">\(\mu\)</span>, <span class="math display">\[
f(\mu) = \pi(\mu)L(\mu) \;\propto\;
\exp\left\{-\frac{(\mu-\mu_0)^2}{2\sigma^2/\kappa_0} - \frac{n(\mu-\bar y)^2}{2\sigma^2}\right\}
\;\propto\; \exp\left\{-\frac{(\mu-\mu_n)^2}{2\sigma^2/\kappa_n}\right\},
\]</span> the kernel of a Normal density with <span class="math display">\[
\kappa_n = \kappa_0+n, \qquad \mu_n = \frac{\kappa_0\mu_0+n\bar y}{\kappa_0+n}.
\]</span> The Normal prior is therefore <strong>conjugate</strong> to the Normal likelihood (known variance), exactly as Beta was to Bernoulli and Gamma to Poisson: <span class="math display">\[
\mu\mid\mathbf y \sim N\!\Big(\mu_n,\ \frac{\sigma^2}{\kappa_n}\Big).
\]</span> As in the other two models, the posterior mean is a pseudo-sample-size weighted average of the prior mean and the MLE <span class="math inline">\(\hat\mu_{\text{MLE}}=\bar y\)</span>, <span class="math display">\[
\mu_n = \underbrace{\frac{\kappa_0}{\kappa_0+n}}_{w}\cdot\mu_0 + (1-w)\cdot\bar y,
\]</span> with prior weight <span class="math inline">\(w=\kappa_0/(\kappa_0+n)\to0\)</span> as <span class="math inline">\(n\to\infty\)</span>, and the posterior “pseudo-sample-sizes” simply <strong>add</strong>: <span class="math inline">\(\kappa_n=\kappa_0+n\)</span> — posterior precision (inverse variance, in units of <span class="math inline">\(1/\sigma^2\)</span>) is prior precision plus data precision.</p>
</section>
<section id="the-marginal-likelihood-in-closed-form-2" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="the-marginal-likelihood-in-closed-form-2"><span class="header-section-number">7.5.3</span> The marginal likelihood in closed form</h3>
<p>Because conjugacy gives the <em>whole</em> posterior in closed form, it also gives the marginal likelihood <span class="math inline">\(P(\mathbf y)=\int f(\mu)\,d\mu\)</span> in closed form. Writing the likelihood with its full normalizing constant, <span class="math inline">\(L(\mu)=(2\pi\sigma^2)^{-n/2}\exp\{-SS/(2\sigma^2)\}\exp\{-n(\mu-\bar y)^2/(2\sigma^2)\}\)</span> with <span class="math inline">\(SS=\sum_{i=1}^n(y_i-\bar y)^2\)</span>, and integrating the same Gaussian-kernel product used to find the posterior above (a standard Gaussian-product identity: <span class="math inline">\(\int\exp\{-a(\mu-m_1)^2/2-b(\mu-m_2)^2/2\}\,d\mu
=\sqrt{2\pi/(a+b)}\exp\{-ab(m_1-m_2)^2/(2(a+b))\}\)</span>) gives <span class="math display">\[
P(\mathbf y) = (2\pi\sigma^2)^{-n/2}\sqrt{\frac{\kappa_0}{\kappa_n}}\,
\exp\left\{-\frac{SS}{2\sigma^2} - \frac{\kappa_0 n(\mu_0-\bar y)^2}{2\sigma^2\kappa_n}\right\}.
\]</span> On the log scale, <span class="math display">\[
\log P(\mathbf y) = -\frac n2\log(2\pi\sigma^2) + \frac12\log\frac{\kappa_0}{\kappa_n}
- \frac{SS}{2\sigma^2} - \frac{\kappa_0 n(\mu_0-\bar y)^2}{2\sigma^2\kappa_n}.
\]</span> As in the other two models, matching the Normal kernel of <span class="math inline">\(f(\mu)\)</span> against its own normalizing constant hands over <span class="math inline">\(P(\mathbf y)\)</span> with no numerical integration.</p>
</section>
<section id="posterior-predictive-in-closed-form-2" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="posterior-predictive-in-closed-form-2"><span class="header-section-number">7.5.4</span> Posterior predictive, in closed form</h3>
<p>For a new <span class="math inline">\(y_{n+1}\mid\mu\sim N(\mu,\sigma^2)\)</span>, integrating the Normal sampling density against the <span class="math inline">\(N(\mu_n,\sigma^2/\kappa_n)\)</span> posterior — a sum of independent Normals — gives another Normal predictive distribution, <span class="math display">\[
y_{n+1}\mid\mathbf y \sim N\!\Big(\mu_n,\ \sigma^2\big(1+\tfrac1{\kappa_n}\big)\Big),
\]</span> with mean equal to the posterior mean of <span class="math inline">\(\mu\)</span> (as it must, by the tower property) and variance <strong>larger</strong> than the known sampling variance <span class="math inline">\(\sigma^2\)</span> by exactly the factor <span class="math inline">\(1+1/\kappa_n\)</span> — the same form as the Gamma–Poisson predictive-variance inflation above, now for a continuous outcome: the extra <span class="math inline">\(1/\kappa_n\)</span> is the leftover posterior uncertainty about <span class="math inline">\(\mu\)</span> leaking into the prediction.</p>
</section>
<section id="worked-numbers-the-complete-inference-output-2" class="level3" data-number="7.5.5">
<h3 data-number="7.5.5" class="anchored" data-anchor-id="worked-numbers-the-complete-inference-output-2"><span class="header-section-number">7.5.5</span> Worked numbers: the complete inference output</h3>
<p>Take a weakly informative prior, <span class="math inline">\(\mu_0=0\)</span> with <span class="math inline">\(\kappa_0=1\)</span> (worth one pseudo-observation), known <span class="math inline">\(\sigma=2\)</span>, and <span class="math inline">\(n=15\)</span> observations simulated from a true mean of <span class="math inline">\(3\)</span>. The table collects the same five quantities as the Beta–Bernoulli and Gamma–Poisson tables above:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sigma_nn <span class="ot">&lt;-</span> <span class="dv">2</span>                                  <span class="co"># known/fixed sigma</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mu0 <span class="ot">&lt;-</span> <span class="dv">0</span>; kappa0 <span class="ot">&lt;-</span> <span class="dv">1</span>                          <span class="co"># N(0, sigma^2/1) prior</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>n_nn <span class="ot">&lt;-</span> <span class="dv">15</span>; y_nn <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n_nn, <span class="dv">3</span>, sigma_nn)   <span class="co"># 15 draws from a true mean of 3</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>ybar_nn <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_nn)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>SS_nn <span class="ot">&lt;-</span> <span class="fu">sum</span>((y_nn <span class="sc">-</span> ybar_nn)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>post_kappa <span class="ot">&lt;-</span> kappa0 <span class="sc">+</span> n_nn</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>post_mu  <span class="ot">&lt;-</span> (kappa0 <span class="sc">*</span> mu0 <span class="sc">+</span> n_nn <span class="sc">*</span> ybar_nn) <span class="sc">/</span> post_kappa</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>post_var <span class="ot">&lt;-</span> sigma_nn<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> post_kappa</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>post_sd  <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(post_var)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>nn_ci    <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), post_mu, post_sd)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>nn_logmarg <span class="ot">&lt;-</span> <span class="sc">-</span>n_nn <span class="sc">/</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">log</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> sigma_nn<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">log</span>(kappa0 <span class="sc">/</span> post_kappa) <span class="sc">-</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  SS_nn <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> sigma_nn<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  kappa0 <span class="sc">*</span> n_nn <span class="sc">*</span> (mu0 <span class="sc">-</span> ybar_nn)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> sigma_nn<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> post_kappa)   <span class="co"># log P(y), exact</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>pred_var <span class="ot">&lt;-</span> post_var <span class="sc">+</span> sigma_nn<span class="sc">^</span><span class="dv">2</span>              <span class="co"># predictive: N(post_mu, pred_var)</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>pred_sd  <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(pred_var)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">quantity =</span> <span class="fu">c</span>(<span class="st">"prior mean"</span>, <span class="st">"MLE ($</span><span class="sc">\\</span><span class="st">bar y$)"</span>, <span class="st">"log marginal likelihood"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"posterior distribution"</span>, <span class="st">"posterior mean"</span>, <span class="st">"posterior sd"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"95% credible interval"</span>, <span class="st">"predictive distribution"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"predictive mean"</span>, <span class="st">"predictive sd"</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, mu0), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, ybar_nn),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, nn_logmarg),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"N(%.3f, %.3f^2)"</span>, post_mu, post_sd),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, post_mu), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, post_sd),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"(%.3f, %.3f)"</span>, nn_ci[<span class="dv">1</span>], nn_ci[<span class="dv">2</span>]),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"N(%.3f, %.3f^2)"</span>, post_mu, pred_sd),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, post_mu), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, pred_sd))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>), <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"quantity"</span>, <span class="st">"value"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-nn-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-nn-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.3: Complete inference output, <span class="math inline">\(N(0, \sigma^2/1)\)</span> prior with known <span class="math inline">\(\sigma=2\)</span>, n = 15.
</figcaption>
<div aria-describedby="tbl-nn-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">quantity</th>
<th style="text-align: left;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">prior mean</td>
<td style="text-align: left;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLE (<span class="math inline">\(\bar y\)</span>)</td>
<td style="text-align: left;">3.305</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log marginal likelihood</td>
<td style="text-align: left;">-31.850</td>
</tr>
<tr class="even">
<td style="text-align: left;">posterior distribution</td>
<td style="text-align: left;">N(3.098, 0.500^2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">posterior mean</td>
<td style="text-align: left;">3.098</td>
</tr>
<tr class="even">
<td style="text-align: left;">posterior sd</td>
<td style="text-align: left;">0.500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">95% credible interval</td>
<td style="text-align: left;">(2.118, 4.078)</td>
</tr>
<tr class="even">
<td style="text-align: left;">predictive distribution</td>
<td style="text-align: left;">N(3.098, 2.062^2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">predictive mean</td>
<td style="text-align: left;">3.098</td>
</tr>
<tr class="even">
<td style="text-align: left;">predictive sd</td>
<td style="text-align: left;">2.062</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>With only <span class="math inline">\(\kappa_0=1\)</span> pseudo-observation against <span class="math inline">\(n=15\)</span> real ones, the posterior mean <span class="math inline">\(3.098\)</span> sits almost on top of the MLE <span class="math inline">\(\bar y=3.305\)</span>, barely pulled toward the prior mean <span class="math inline">\(0\)</span> — the same shrinkage story as the two examples above, now driven by <span class="math inline">\(\kappa_0\)</span> instead of <span class="math inline">\(\alpha_0+\alpha_1\)</span> or <span class="math inline">\(\beta\)</span>. The predictive sd <span class="math inline">\(2.062\)</span> exceeds the known <span class="math inline">\(\sigma=2\)</span> by the factor <span class="math inline">\(\sqrt{1+1/\kappa_n}=\sqrt{1.062}\)</span> derived above — the continuous analogue of the Gamma–Poisson overdispersion factor.</p>
</section>
<section id="overdispersion-visualized-1" class="level3" data-number="7.5.6">
<h3 data-number="7.5.6" class="anchored" data-anchor-id="overdispersion-visualized-1"><span class="header-section-number">7.5.6</span> Overdispersion, visualized</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>)); pred_sd <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(post_var <span class="sc">+</span> sigma_nn<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, post_mu, pred_sd), post_mu <span class="sc">-</span> <span class="dv">4</span> <span class="sc">*</span> pred_sd, post_mu <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> pred_sd,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(y[n<span class="sc">+</span><span class="dv">1</span>]), <span class="at">ylab =</span> <span class="st">"density"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, post_mu, sigma_nn), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray40"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"gray40"</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"posterior predictive"</span>, <span class="st">"plug-in Normal at posterior mean"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-nn-predictive-dispersion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-predictive-dispersion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit07_bayesian_inference_files/figure-html/fig-nn-predictive-dispersion-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-predictive-dispersion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.6: Posterior predictive <span class="math inline">\(N(\mu_n, \sigma^2(1+1/\kappa_n))\)</span> (red, solid) against a plug-in <span class="math inline">\(N(\mu_n,\sigma^2)\)</span> at the posterior mean (gray, dashed). Same mean, but the predictive is visibly wider — the extra spread is entirely the remaining posterior uncertainty about <span class="math inline">\(\mu\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-bayes-explorer" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="sec-bayes-explorer"><span class="header-section-number">7.6</span> Explore it interactively</h2>
<p>This app runs live only in the HTML edition of this book; readers of other formats can follow the link below it.</p>
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bayes-explorer-app-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<pre class="shinylive-r" data-engine="r"><code>#| '!! shinylive warning !!': |
#|   shinylive does not work in self-contained HTML documents.
#|   Please set `embed-resources: false` in your metadata.
#| label: bayes-explorer-app
#| standalone: true
#| viewerHeight: 800

library(shiny)

ui &lt;- fluidPage(
  titlePanel(NULL),
  sidebarLayout(
    sidebarPanel(
      width = 4,
      selectInput("model", "Model",
                  choices = c("Bernoulli - Beta" = "bb", "Poisson - Gamma" = "pg",
                              "Normal (known sigma) - Normal" = "nn")),
      conditionalPanel(
        "input.model == 'bb'",
        numericInput("a1", "prior alpha1 (successes)", value = 1, min = 0.1, step = 0.5),
        numericInput("a0", "prior alpha0 (failures)", value = 1, min = 0.1, step = 0.5),
        numericInput("n_bb", "n (trials)", value = 10, min = 1, step = 1),
        numericInput("y_bb", "y (successes observed)", value = 7, min = 0, step = 1)
      ),
      conditionalPanel(
        "input.model == 'pg'",
        numericInput("alpha", "prior alpha (shape)", value = 2, min = 0.1, step = 0.5),
        numericInput("beta", "prior beta (rate)", value = 1, min = 0.1, step = 0.5),
        numericInput("n_pg", "n (observations)", value = 8, min = 1, step = 1),
        numericInput("S_pg", "sum of counts", value = 29, min = 0, step = 1)
      ),
      conditionalPanel(
        "input.model == 'nn'",
        numericInput("mu0", "prior mu0 (mean)", value = 0, step = 0.5),
        numericInput("kappa0", "prior kappa0 (pseudo-sample-size)", value = 1, min = 0.1, step = 0.5),
        numericInput("sigma_nn", "sigma (known)", value = 2, min = 0.1, step = 0.5),
        numericInput("n_nn", "n (observations)", value = 15, min = 1, step = 1),
        numericInput("ybar_nn", "sample mean y-bar", value = 3, step = 0.5)
      ),
      helpText("Dashed = prior, solid = posterior. The dotted vertical line ",
               "is the MLE (y/n for Bernoulli, S/n for Poisson, y-bar for Normal). ",
               "*Log marginal likelihood is exact for Bernoulli; for Poisson ",
               "and Normal it is shown up to an additive constant that ",
               "depends only on the individual data points (not part of the ",
               "summary inputs here) and cancels when comparing priors for ",
               "the same data.")
    ),
    mainPanel(
      width = 8,
      plotOutput("densplot", height = "380px"),
      tableOutput("summtab")
    )
  )
)

server &lt;- function(input, output, session) {

  output$densplot &lt;- renderPlot({
    par(mar = c(4, 4, 2, 1))
    if (input$model == "bb") {
      a1 &lt;- input$a1; a0 &lt;- input$a0; n &lt;- input$n_bb; y &lt;- input$y_bb
      post_a1 &lt;- a1 + y; post_a0 &lt;- a0 + (n - y)
      xs &lt;- seq(0, 1, length.out = 500)
      ylim &lt;- c(0, max(dbeta(xs, a1, a0), dbeta(xs, post_a1, post_a0)) * 1.1)
      curve(dbeta(x, a1, a0), 0, 1, lwd = 2, lty = 2, col = "gray40",
            xlab = expression(theta), ylab = "density", ylim = ylim)
      curve(dbeta(x, post_a1, post_a0), add = TRUE, lwd = 3, col = "steelblue")
      abline(v = y / n, lty = 3)
      legend("topright", bty = "n", lwd = c(2, 3), lty = c(2, 1), col = c("gray40", "steelblue"),
             legend = c("prior", "posterior"))
    } else if (input$model == "pg") {
      alpha &lt;- input$alpha; beta &lt;- input$beta; n &lt;- input$n_pg; S &lt;- input$S_pg
      post_alpha &lt;- alpha + S; post_beta &lt;- beta + n
      hi &lt;- max(qgamma(0.999, alpha, beta), qgamma(0.999, post_alpha, post_beta))
      xs &lt;- seq(0, hi, length.out = 500)
      ylim &lt;- c(0, max(dgamma(xs, alpha, beta), dgamma(xs, post_alpha, post_beta)) * 1.1)
      curve(dgamma(x, alpha, beta), 0, hi, lwd = 2, lty = 2, col = "gray40",
            xlab = expression(lambda), ylab = "density", ylim = ylim)
      curve(dgamma(x, post_alpha, post_beta), add = TRUE, lwd = 3, col = "firebrick")
      abline(v = S / n, lty = 3)
      legend("topright", bty = "n", lwd = c(2, 3), lty = c(2, 1), col = c("gray40", "firebrick"),
             legend = c("prior", "posterior"))
    } else {
      mu0 &lt;- input$mu0; kappa0 &lt;- input$kappa0; sigma &lt;- input$sigma_nn
      n &lt;- input$n_nn; ybar &lt;- input$ybar_nn
      post_kappa &lt;- kappa0 + n
      post_mu &lt;- (kappa0 * mu0 + n * ybar) / post_kappa
      post_sd &lt;- sigma / sqrt(post_kappa)
      prior_sd &lt;- sigma / sqrt(kappa0)
      lo &lt;- min(mu0 - 3 * prior_sd, post_mu - 3 * post_sd)
      hi &lt;- max(mu0 + 3 * prior_sd, post_mu + 3 * post_sd)
      xs &lt;- seq(lo, hi, length.out = 500)
      ylim &lt;- c(0, max(dnorm(xs, mu0, prior_sd), dnorm(xs, post_mu, post_sd)) * 1.1)
      curve(dnorm(x, mu0, prior_sd), lo, hi, lwd = 2, lty = 2, col = "gray40",
            xlab = expression(mu), ylab = "density", ylim = ylim)
      curve(dnorm(x, post_mu, post_sd), add = TRUE, lwd = 3, col = "darkorchid")
      abline(v = ybar, lty = 3)
      legend("topright", bty = "n", lwd = c(2, 3), lty = c(2, 1), col = c("gray40", "darkorchid"),
             legend = c("prior", "posterior"))
    }
  })

  output$summtab &lt;- renderTable({
    if (input$model == "bb") {
      a1 &lt;- input$a1; a0 &lt;- input$a0; n &lt;- input$n_bb; y &lt;- input$y_bb
      post_a1 &lt;- a1 + y; post_a0 &lt;- a0 + (n - y)
      logmarg    &lt;- lbeta(post_a1, post_a0) - lbeta(a1, a0)         # exact
      pred_mean  &lt;- post_a1 / (post_a1 + post_a0)
      pred_sd    &lt;- sqrt(pred_mean * (1 - pred_mean))
      data.frame(
        quantity = c("prior mean", "MLE (y/n)", "log marginal likelihood*",
                     "posterior distribution", "posterior mean", "posterior sd",
                     "95% credible interval", "predictive distribution",
                     "predictive mean", "predictive sd"),
        value = c(sprintf("%.3f", a1 / (a1 + a0)),
                  sprintf("%.3f", y / n),
                  sprintf("%.3f", logmarg),
                  sprintf("Beta(%.2f, %.2f)", post_a1, post_a0),
                  sprintf("%.3f", pred_mean),
                  sprintf("%.3f", sqrt(post_a1 * post_a0 / ((post_a1 + post_a0)^2 * (post_a1 + post_a0 + 1)))),
                  sprintf("(%.3f, %.3f)", qbeta(0.025, post_a1, post_a0), qbeta(0.975, post_a1, post_a0)),
                  sprintf("Bernoulli(%.3f)", pred_mean),
                  sprintf("%.3f", pred_mean), sprintf("%.3f", pred_sd)))
    } else if (input$model == "pg") {
      alpha &lt;- input$alpha; beta &lt;- input$beta; n &lt;- input$n_pg; S &lt;- input$S_pg
      post_alpha &lt;- alpha + S; post_beta &lt;- beta + n
      logmarg   &lt;- alpha * log(beta) - lgamma(alpha) + lgamma(post_alpha) -
        post_alpha * log(post_beta)                                 # up to -sum(log(y_i!))
      nb_prob   &lt;- post_beta / (post_beta + 1)
      pred_mean &lt;- post_alpha / post_beta
      pred_sd   &lt;- sqrt(pred_mean * (1 + 1 / post_beta))
      data.frame(
        quantity = c("prior mean", "MLE (S/n)", "log marginal likelihood*",
                     "posterior distribution", "posterior mean", "posterior sd",
                     "95% credible interval", "predictive distribution",
                     "predictive mean", "predictive sd"),
        value = c(sprintf("%.3f", alpha / beta),
                  sprintf("%.3f", S / n),
                  sprintf("%.3f", logmarg),
                  sprintf("Gamma(%.2f, %.2f)", post_alpha, post_beta),
                  sprintf("%.3f", pred_mean),
                  sprintf("%.3f", sqrt(post_alpha) / post_beta),
                  sprintf("(%.3f, %.3f)", qgamma(0.025, post_alpha, post_beta), qgamma(0.975, post_alpha, post_beta)),
                  sprintf("NegBin(%.2f, %.3f)", post_alpha, nb_prob),
                  sprintf("%.3f", pred_mean), sprintf("%.3f", pred_sd)))
    } else {
      mu0 &lt;- input$mu0; kappa0 &lt;- input$kappa0; sigma &lt;- input$sigma_nn
      n &lt;- input$n_nn; ybar &lt;- input$ybar_nn
      post_kappa &lt;- kappa0 + n
      post_mu &lt;- (kappa0 * mu0 + n * ybar) / post_kappa
      post_sd &lt;- sigma / sqrt(post_kappa)
      logmarg &lt;- -n / 2 * log(2 * pi * sigma^2) + 0.5 * log(kappa0 / post_kappa) -
        kappa0 * n * (mu0 - ybar)^2 / (2 * sigma^2 * post_kappa)     # up to -SS/(2 sigma^2)
      pred_sd &lt;- sqrt(post_sd^2 + sigma^2)
      data.frame(
        quantity = c("prior mean", "MLE (y-bar)", "log marginal likelihood*",
                     "posterior distribution", "posterior mean", "posterior sd",
                     "95% credible interval", "predictive distribution",
                     "predictive mean", "predictive sd"),
        value = c(sprintf("%.3f", mu0),
                  sprintf("%.3f", ybar),
                  sprintf("%.3f", logmarg),
                  sprintf("N(%.3f, %.3f^2)", post_mu, post_sd),
                  sprintf("%.3f", post_mu),
                  sprintf("%.3f", post_sd),
                  sprintf("(%.3f, %.3f)", qnorm(0.025, post_mu, post_sd), qnorm(0.975, post_mu, post_sd)),
                  sprintf("N(%.3f, %.3f^2)", post_mu, pred_sd),
                  sprintf("%.3f", post_mu), sprintf("%.3f", pred_sd)))
    }
  }, colnames = FALSE, striped = TRUE)
}

shinyApp(ui, server)</code></pre>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bayes-explorer-app-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.7: <strong>Shinylive App Illustrating Conjugate Bayesian Updating.</strong> The app below lets you adjust the prior, sample size, and observed data for any of the three conjugate models and watch prior and posterior move together, along with the posterior summary table computed above.
</figcaption>
</figure>
</section>
<section id="where-computation-enters" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="where-computation-enters"><span class="header-section-number">7.7</span> Where Computation Enters</h2>
<p>For the Beta–Bernoulli, Gamma–Poisson, and Normal–Normal models, everything above is closed-form: the posterior, its mean and variance, credible intervals, and even the marginal likelihood and predictive distribution. Conjugacy is a special convenience, restricted to a handful of prior/likelihood pairings; for a general model, the same quantities require genuine numerical work:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Requires</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Normalizing constant <span class="math inline">\(P(\mathbf y) = \int L(\theta)\pi(\theta)\,d\theta\)</span></td>
<td style="text-align: left;">integration over <span class="math inline">\(\theta\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Posterior mean, variance, probabilities</td>
<td style="text-align: left;">integration over <span class="math inline">\(\theta\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Posterior mode</td>
<td style="text-align: left;">optimization</td>
</tr>
<tr class="even">
<td style="text-align: left;">Posterior predictive <span class="math inline">\(\int P(y_{n+1}\mid\theta)P(\theta\mid\mathbf y)\,d\theta\)</span></td>
<td style="text-align: left;">integration over <span class="math inline">\(\theta\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Credible intervals</td>
<td style="text-align: left;">posterior quantiles</td>
</tr>
</tbody>
</table>
<p>The strategy depends on the dimension of <span class="math inline">\(\theta\)</span>. For <strong>one-dimensional</strong> <span class="math inline">\(\theta\)</span>, a deterministic grid of evaluation points — <strong>numerical quadrature</strong>, the next chapter — is cheap and accurate, and <strong>Laplace’s method</strong> (the chapter after that) offers a grid-free alternative built from just the posterior mode and its curvature, at the cost of assuming the posterior is roughly bell-shaped. For <strong>multi-dimensional</strong> <span class="math inline">\(\theta\)</span>, a grid becomes exponentially expensive, and the standard approach is Monte Carlo: approximate every integral by an average over posterior draws <span class="math inline">\(\theta_1,\ldots,\theta_J\sim P(\theta\mid\mathbf y)\)</span>, as prediction already did above. Producing those draws — by <strong>rejection sampling</strong>, <strong>importance sampling</strong>, and finally <strong>Markov chain Monte Carlo</strong> — is the subject of the remaining chapters of this book.</p>
</section>
<section id="summary" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="summary"><span class="header-section-number">7.8</span> Summary</h2>
<ul>
<li>Bayesian inference treats <span class="math inline">\(\theta\)</span> as random, combines a prior <span class="math inline">\(\pi(\theta)\)</span> with a likelihood <span class="math inline">\(L(\theta)\)</span> via Bayes’ rule, and reports a <em>distribution</em> <span class="math inline">\(P(\theta\mid\mathbf y)\propto f(\theta)=L(\theta)\pi(\theta)\)</span> rather than a single point estimate.</li>
<li>Every standard summary — posterior mean/median/mode, credible intervals, predictive distributions — is an integral or an optimization over that posterior, which is why Bayesian inference is a computational subject.</li>
<li>The Beta–Bernoulli, Gamma–Poisson, and Normal–Normal (known variance) pairs are <strong>conjugate</strong>: the posterior is available in closed form (Beta, Gamma, and Normal respectively), the posterior mean is an exact weighted average of the prior mean and the MLE with the prior’s pseudo-sample-size as weight, and the marginal likelihood and predictive distribution are closed-form too (Negative Binomial for Gamma–Poisson, Normal with inflated variance for Normal–Normal) — no integration needed anywhere.</li>
<li>The Gamma–Poisson predictive distribution is visibly overdispersed relative to a plug-in Poisson at the posterior mean rate, by an exact factor <span class="math inline">\(1+1/(\beta+n)\)</span>: real posterior uncertainty about <span class="math inline">\(\theta\)</span> widens predictions, a general feature the closed form makes precise here.</li>
<li>Conjugacy is the exception, not the rule. The rest of this book develops general-purpose tools for the same four computations — quadrature, Laplace approximation, rejection sampling, importance sampling, and MCMC — for models where no such algebraic shortcut exists.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>