{
  "hash": "99cdc80ae6cb935365c0ab4de4dac1c6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Computer Arithmetic\neditor_options:\n  chunk_output_type: console\n---\n\n```{=html}\n<style>\n.pv table { border-collapse: collapse; margin: 0.6em auto; font-family: monospace; }\n.pv td, .pv th { border: 2px solid #555; min-width: 2em; height: 1.5em;\n                 text-align: center !important; padding: 0.3em 0.3em; font-size: 0.95em; }\n.pv th { border: none; font-size: 0.7em; color: #666; font-weight: normal; }\n.pv td.s { background: #fbe4ec; }   /* sign */\n.pv td.m { background: #e3eefb; }   /* mantissa / digits */\n.pv td.e { background: #e7f6e0; }   /* exponent */\n.pv td.x { background: #ffd6d6; color: #b00000; font-weight: bold; } /* lost / invalid */\n.pv td.p { border: none; padding: 0; min-width: 0; font-weight: bold; } /* punctuation */\n.pv .cap { font-size: 0.85em; color: #444; text-align: center !important; margin-top: -0.3em; }\n</style>\n```\n\nStatistical computation is arithmetic on a machine that stores every number in a fixed number of binary digits. This chapter describes how integers and real numbers are represented, what goes wrong when a computation exceeds the capacity of that representation (overflow, underflow, and roundoff error), and the standard techniques for writing statistical code that avoids these failures: reordering sums, rewriting formulas, and working on the logarithmic scale.\n\n## Representations of Numbers in Computer\n\n### Place value\n\nEvery number is a string of digits in boxes, and each box has a **place value**. In base 10,\n\n::: {.pv}\n<table>\n<tr><th>10³</th><th>10²</th><th>10¹</th><th>10⁰</th></tr>\n<tr><td class=\"m\">1</td><td class=\"m\">3</td><td class=\"m\">4</td><td class=\"m\">8</td></tr>\n</table>\n<p class=\"cap\">$1348 = 1\\times10^3 + 3\\times10^2 + 4\\times10^1 + 8\\times10^0$</p>\n\n:::\n\nA computer uses base 2, so each box, called a **bit**, holds 0 or 1:\n\n::: {.pv}\n<table>\n<tr><th>2³</th><th>2²</th><th>2¹</th><th>2⁰</th></tr>\n<tr><td class=\"m\">1</td><td class=\"m\">1</td><td class=\"m\">0</td><td class=\"m\">1</td></tr>\n</table>\n<p class=\"cap\">$1101_2 = 1\\times2^3 + 1\\times2^2 + 0\\times2^1 + 1\\times2^0 = 13$</p>\n\n:::\n\nEverything that follows is a consequence of one fact: the number of boxes is fixed in advance.\n\n### Integers\n\nAn integer is stored in a fixed number of bits, typically 32 or 64. With $p$ bits the largest unsigned value is obtained by filling every box with 1,\n$$\n\\sum_{i=0}^{p-1} 2^i = 2^p - 1 .\n$$\nA 4-bit example: the largest storable integer is $1111_2 = 15$, and $15 + 1 = 16 = 10000_2$ needs a fifth box that does not exist.\n\n::: {.pv}\n<table>\n<tr><th>2⁴</th><th>2³</th><th>2²</th><th>2¹</th><th>2⁰</th></tr>\n<tr><td class=\"x\">1</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td></tr>\n</table>\n<p class=\"cap\">The leading 1 has nowhere to go: **integer overflow**</p>\n:::\n\nTo represent negative values, one of the boxes is used as a **sign bit**, leaving $p-1$ boxes for the magnitude. With 32 bits, a signed integer $u$ is\n$$\nu = (-1)^{s}\\sum_{i=0}^{30} d_i\\,2^i, \\qquad s\\in\\{0,1\\}.\n$$\nThe largest integer has the sign bit $0$ and the other 31 boxes all equal to $1$:\n\n::: {.pv}\n<table>\n<tr><th>sign</th><th>2³⁰</th><th>2²⁹</th><th>…</th><th>2¹</th><th>2⁰</th></tr>\n<tr><td class=\"s\">+</td><td class=\"m\">1</td><td class=\"m\">1</td><td class=\"m\">…</td><td class=\"m\">1</td><td class=\"m\">1</td></tr>\n</table>\n<p class=\"cap\">$u^{\\max} = \\sum_{i=0}^{30} 2^i = 2^{31}-1 = 2147483647$</p>\n:::\n\nand the smallest is its negative, $u^{\\min} = -(2^{31}-1)$. When an integer computation leaves this range, R does not wrap around silently, as C does; it returns `NA` with a warning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.Machine$integer.max\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2147483647\n```\n\n\n:::\n\n```{.r .cell-code}\n## Check upper bounds\nas.integer(2^31 - 1)                    # maximum valid integer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2147483647\n```\n\n\n:::\n\n```{.r .cell-code}\nas.integer(2^31)                        # exceeds limit, returns NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nas.integer(2^31 - 1) + as.integer(1)    # overflows to NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\n## Check lower bounds\nas.integer(-(2^31 - 1))                 # minimum valid integer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2147483647\n```\n\n\n:::\n\n```{.r .cell-code}\nas.integer(-2^31)                       # exceeds lower limit, returns NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\nA practical consequence: products of moderately large integers overflow easily. `50000L * 50000L` is `NA` in R, while `50000 * 50000` (double precision) is fine. R converts to double automatically for most arithmetic, so integer overflow is rarely a problem in R code; it is a common one in C, Java, and database systems.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n50000L * 50000L\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\n50000 * 50000\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.5e+09\n```\n\n\n:::\n:::\n\n\n### Floating point numbers\n\nA real number is stored in the form of scientific notation: a **sign**, a **mantissa** holding the significant digits, and an **exponent**:\n$$\nx = (-1)^{s} \\times 1.d_1 d_2 \\cdots d_p \\times 2^{\\,e}.\n$$\n\n::: {.pv}\n<table>\n<tr><th>sign</th><th colspan=\"4\">mantissa (fixed number of digits)</th><th></th><th colspan=\"2\">exponent</th></tr>\n<tr><td class=\"s\">+</td><td class=\"m\">1</td><td class=\"p\">.</td><td class=\"m\">d₁</td><td class=\"m\">d₂ … d<sub>p</sub></td><td class=\"p\">×2^</td><td class=\"s\">±</td><td class=\"e\">e</td></tr>\n</table>\n\n:::\n\nMore precisely, a floating point number $x$ is represented by a vector of bits $(s,d_0,\\ldots,d_{t-1},e_1,\\ldots, e_{k-1})$ as,\n$$\nx = (-1)^s \\sum_{i=0}^{t-1}d_i2^{-i}\\times 2^{\\sum_{i=0}^{k-1}e_i2^i-2^{k-1}}.\n$$\nThe leading mantissa bit is always 1 for a normalized number and need not be stored, and the exponent is stored with an offset so that both negative and positive exponents fit in unsigned bits. Double precision (`double` in R, the IEEE 754 standard) uses 64 bits:\n\n| part | bits | consequence |\n|:-|:-:|:----------|\n| sign | 1 | |\n| mantissa | 52 | about 16 significant decimal digits |\n| exponent | 11 | $e \\in [-1022,\\ 1023]$, i.e. magnitudes from $10^{-308}$ to $10^{308}$ |\n\n### A toy floating point system\n\nTo see what goes wrong, it is easier to work in a decimal toy computer with a **4-digit mantissa** and a **1-digit exponent**, $e\\in[-9,9]$:\n\n::: {.pv}\n<table>\n<tr><th>sign</th><th>1</th><th></th><th>10⁻¹</th><th>10⁻²</th><th>10⁻³</th><th></th><th>exp</th></tr>\n<tr><td class=\"s\">+</td><td class=\"m\">3</td><td class=\"p\">.</td><td class=\"m\">1</td><td class=\"m\">4</td><td class=\"m\">2</td><td class=\"p\">×10^</td><td class=\"e\">0</td></tr>\n</table>\n<p class=\"cap\">$3.142\\times10^{0}$, the closest storable value to $\\pi$</p>\n\n:::\n\nThree things can go wrong, all caused by the boxes being finite:\n\n1. **Overflow**: the exponent box is too small for a large number.\n\n2. **Underflow**: the exponent box is too small for a tiny number.\n3. **Roundoff**: the mantissa boxes are too few for all the digits.\n\n### Significance of the Mantissa: A Zoom Model\n\nThink of a floating point number as a **ruler** and a **zoom setting**. The mantissa is a fixed ruler with equally spaced marks; the exponent is a zoom factor $10^{e}$ that stretches the ruler to cover the interval $[10^{e}, 10^{e+1})$. The number of marks never changes, so the more the ruler is stretched, the farther apart the marks land on the number line.\n\nThe simplest case has a **one-digit mantissa**: the ruler has nine marks, $1, 2, \\ldots, 9$, and a number is stored as $d\\times10^{e}$ with $d\\in\\{1,\\ldots,9\\}$.\n\n::: {.pv}\n<table>\n<tr><th>1</th><th></th><th>exp</th></tr>\n<tr><td class=\"m\">d</td><td class=\"p\">×10^</td><td class=\"e\">e</td></tr>\n</table>\n<p class=\"cap\">One mantissa digit: the ruler marks are $1\\times10^{e}, 2\\times10^{e}, \\ldots, 9\\times10^{e}$</p>\n:::\n\n| zoom $e$ | interval $[10^e, 10^{e+1})$ | storable numbers | gap |\n|:--:|:--|:--|:--:|\n| 0 | $[1, 10)$ | $1, 2, 3, \\ldots, 9$ | $1$ |\n| 1 | $[10, 100)$ | $10, 20, 30, \\ldots, 90$ | $10$ |\n| 2 | $[100, 1000)$ | $100, 200, \\ldots, 900$ | $100$ |\n| $-1$ | $[0.1, 1)$ | $0.1, 0.2, \\ldots, 0.9$ | $0.1$ |\n\nWithin each zoom level the storable numbers are evenly spaced, and the spacing is multiplied by $10$ each time the zoom goes up one level. Every real number between two marks is rounded to the nearer mark: $24\\to20$, $27\\to30$, $2.4\\to2$, and $0.27\\to0.3$.\n\nAdding mantissa digits adds marks to the ruler without changing the zoom mechanism. With a leading digit and $t$ further digits there are $9\\times10^{t}$ marks in $[10^e, 10^{e+1})$, and the gap at zoom $e$ is $10^{e-t}$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Representable numbers in $[1, 100)$ for a mantissa of 1 and 2 decimal digits. The two zoom levels $[1, 10)$ and $[10, 100)$ are shaded; within each, the marks are evenly spaced, and the spacing is ten times larger at the higher zoom.](unit02_comparith_files/figure-html/fig-zoom-model-1.png){#fig-zoom-model width=864}\n:::\n:::\n\n\nThe picture explains the two facts that matter for computation:\n\n- The **absolute** gap grows with the magnitude, because the same ruler is stretched more; the **relative** gap, gap divided by magnitude, stays between $10^{-t}$ and $10^{-t-1}$ at every zoom level.\n- The relative gap near $1$ is the **machine epsilon** $\\epsilon$: the smallest $\\epsilon$ such that $1+\\epsilon \\neq 1$ on the computer. It is the distance between the first two marks of the ruler at zoom $e = 0$. In the one-digit system $\\epsilon = 1$, so $1 + 0.4$ rounds back to $1$; in the four-digit toy system $\\epsilon = 0.001$.\n\nA binary computer works the same way with a ruler of $2^{t}$ marks per doubling instead of $9\\times10^{t}$ marks per decade. For doubles, $t = 52$ and $\\epsilon = 2^{-52}\\approx 2.2\\times10^{-16}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.Machine$double.eps      # 2^-52\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.220446e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + 2^-52 == 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + 2^-53 == 1           # half an epsilon rounds back to 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nFor doubles the gap at zoom level $[2^e, 2^{e+1})$ is $2^{e-52}$. Near $2^{52}$ the spacing is exactly $1$, and in $[2^{53}, 2^{54})$ it is $2$, so odd integers can no longer be represented.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2^52 + 1 == 2^52             # spacing is 1: still distinguishable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n2^53 + 1 == 2^53             # spacing is 2: the +1 is lost\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nformat(c(2^53, 2^53 + 1, 2^53 + 2), digits = 17)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"9007199254740992\" \"9007199254740992\" \"9007199254740994\"\n```\n\n\n:::\n:::\n\n\nThis is why a `double` can hold every integer only up to $2^{53}\\approx 9\\times10^{15}$, and why counters or identifiers above that size must be kept as integers or character strings.\n\n### Overflow and underflow\n\nThe largest toy number fills every box with 9, $9.999\\times10^{9}$. The next number, $10^{10}$, needs an exponent of two digits and cannot be stored: this is **overflow**, and the result is recorded as `Inf`. At the other end, $10^{-9}$ is the smallest positive toy number, and $10^{-10}$ **underflows** to $0$.\n\n::: {.pv}\n<table>\n<tr><td class=\"s\">+</td><td class=\"m\">1</td><td class=\"p\">.</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"p\">×10^</td><td class=\"x\">10</td></tr>\n</table>\n<p class=\"cap\">$10^{10}$: overflow, stored as `Inf`</p>\n<table>\n<tr><td class=\"s\">+</td><td class=\"m\">1</td><td class=\"p\">.</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"p\">×10^</td><td class=\"x\">-10</td></tr>\n</table>\n<p class=\"cap\">$10^{-10}$: underflow, stored as `0`</p>\n\n:::\n\nFor doubles the largest value is about $1.8\\times10^{308}$ (just below $2^{1024}$). The smallest positive value with full 52-bit precision is $2^{-1022}\\approx 2.2\\times10^{-308}$; below that, the IEEE standard allows \"subnormal\" numbers with progressively fewer significant bits down to $2^{-1074}\\approx 4.9\\times10^{-324}$, after which the value is $0$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Overflow and underflow regions on the number line for double precision](unit02_comparith_files/figure-html/fig-number-line-1.png){#fig-number-line fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## largest double precision floating-point number\n.Machine$double.xmax\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.797693e+308\n```\n\n\n:::\n\n```{.r .cell-code}\n2^1023\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.988466e+307\n```\n\n\n:::\n\n```{.r .cell-code}\n2^1024          # overflows to Inf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Inf\n```\n\n\n:::\n\n```{.r .cell-code}\n## smallest double precision floating-point numbers\n.Machine$double.xmin   # smallest with full precision, 2^-1022\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.225074e-308\n```\n\n\n:::\n\n```{.r .cell-code}\n2^(-1074)              # smallest subnormal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.940656e-324\n```\n\n\n:::\n\n```{.r .cell-code}\n2^(-1075)              # underflows to 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nOverflow is loud: `Inf` propagates and usually produces `NaN` or an error somewhere downstream. Underflow is quiet: a probability that underflows to $0$ simply produces `log(0) = -Inf` or a likelihood ratio of `0/0`, and the code may run to completion with a wrong answer.\n\n## Rounding Error and Methods for Preventing It\n\n### Roundoff error\n\nCompute $1 + 0.0001$ in the toy system. The exact answer $1.0001$ needs a fifth mantissa box:\n\n::: {.pv}\n<table>\n<tr><th></th><th>1</th><th></th><th>10⁻¹</th><th>10⁻²</th><th>10⁻³</th><th>10⁻⁴</th><th></th><th>exp</th></tr>\n<tr><td class=\"s\">+</td><td class=\"m\">1</td><td class=\"p\">.</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"x\">1</td><td class=\"p\">×10^</td><td class=\"e\">0</td></tr>\n</table>\n<p class=\"cap\">The red digit does not fit and is rounded away: the stored result is exactly $1.000$</p>\n\n:::\n\nIn general the stored result of $a+b$ (or $a\\times b$, $a/b$, …) is the **nearest representable number** to the exact result. Each single operation therefore has relative error at most about $\\epsilon$, which is harmless on its own. The concern is when these errors **accumulate** over many operations or are **amplified** by the structure of a formula. Two patterns do the amplifying:\n\n- adding a **large + small** number, where the small number is partly or wholly rounded away;\n\n- subtracting **large − large** nearly equal numbers, where the leading digits cancel and only the roundoff errors survive (**catastrophic cancellation**).\n\n### Computing sums: avoiding large + small\n\nThe mantissa has a finite capacity, so adding something extremely small, like $2^{-54}$, to $1$ loses the small term entirely because its bits fall outside the 52 stored digits.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Roundoff error when adding a large and a small number](unit02_comparith_files/figure-html/fig-large-plus-small-1.png){#fig-large-plus-small fig-align='center' width=672}\n:::\n:::\n\n\nConsider $1 + 0.0001 + 0.0001$ in the toy system. Evaluated left to right, $(1 + 0.0001) + 0.0001$, the first addition rounds to $1.000$, and so does the second: both small terms are lost. Evaluated as $1 + (0.0001 + 0.0001) = 1 + 0.0002$, the intermediate sum $2.000\\times10^{-4}$ is exact, and only the final addition rounds. With four mantissa digits the final result is still $1.000$, but the point is general: adding the small terms among themselves first commits only **one** roundoff error, whereas adding them one at a time to the large number commits one per term, and these accumulate.\n\nThe following R demonstration makes the same point at machine precision. `f2` attempts to add $2^{-53}$ (half an epsilon) $2^{13}$ times, but because $1 + 2^{-53} = 1$ at every single step, the final sum is simply $1$ instead of $1 + 2^{-40}$. Grouping the small numbers and adding them together before adding them to the large number (`f6s`) recovers the correct answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## the target value\nf0 <- 1 + 2^(-40)\nf0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n## adding 2^-52 (one epsilon) 2^12 times works: each addition changes the sum\nf1 <- 1; i <- 1\nwhile (i <= 2^12) { f1 <- f1 + 2^(-52); i <- i + 1 }\nf1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n## adding 2^-53 (half an epsilon) 2^13 times fails: 1 + 2^-53 rounds to 1 every time\nf2 <- 1; i <- 1\nwhile (i <= 2^13) { f2 <- f2 + 2^(-53); i <- i + 1 }\nf2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n## this difference is not due to number display in R\nf0 == f1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nf0 == f2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n## R's built-in sum() uses pairwise summation and extended precision\nf3 <- sum(c(1, rep(2^(-53), 2^13))); f3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nf1 == f3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nf4 <- sum(c(1, rep(2^(-54), 2^14))); f4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nf0 == f4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n## the fix: accumulate the small numbers first, then add to 1\nf6s <- 0; i <- 1\nwhile (i <= 2^14) { f6s <- f6s + 2^(-54); i <- i + 1 }\nf6s\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.094947e-13\n```\n\n\n:::\n\n```{.r .cell-code}\nf6 <- f6s + 1; f6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nf0 == f6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n#### Rules for accurate summation {-}\n- Add numbers of similar magnitude together; when summing terms of very different sizes, add the smallest first (sort ascending).\n\n- **Pairwise summation**: sum the two halves of the vector recursively, so that partial sums stay of similar size. R's `sum()` uses this together with extended-precision accumulation, which is why `sum()` beat the naive loop above.\n- **Kahan compensated summation**: keep track of the part rounded away at each step and add it back at the next step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(1, rep(1e-16, 1e4))                 # exact sum is 1 + 1e-12\n\nnaive_sum <- function(x) { s <- 0; for (v in x) s <- s + v; s }\n\nkahan_sum <- function(x) {\n  s <- 0; c <- 0                            # c holds the running roundoff error\n  for (v in x) { y <- v - c; t <- s + y; c <- (t - s) - y; s <- t }\n  s }\n\nc(naive   = naive_sum(x) - 1,\n  sorted  = naive_sum(sort(x)) - 1,\n  kahan   = kahan_sum(x) - 1,\n  builtin = sum(x) - 1,\n  exact   = 1e-12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       naive       sorted        kahan      builtin        exact \n0.000000e+00 1.000089e-12 1.000089e-12 0.000000e+00 1.000000e-12 \n```\n\n\n:::\n:::\n\n\nThe naive loop loses every one of the $10^4$ small terms; sorting recovers most of the answer, and Kahan summation and R's `sum()` recover it to full precision.\n\nWe can use `log()` to translate the 52-bit limit into other bases, which tells us at roughly what decimal place precision is lost (about 15 to 16 significant decimal digits).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog(2^(-52))               # base e: about -36\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -36.04365\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + exp(-35)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + exp(-37)               # evaluates to exactly 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2^(-52), base = 10)    # base 10: about -15.7\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -15.65356\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + 1e-15 == 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + 1e-16 == 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### Computing $e^x$: avoiding large − large\n\nThe Taylor series,\n$$\ne^x \\approx \\sum_{k=0}^{K}\\frac{x^k}{k!} = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\cdots,\n$$\nworks well for $x > 0$ but fails for large negative $x$. For $x = -20$ the terms alternate in sign and are huge relative to the answer $e^{-20}\\approx 2\\times10^{-9}$:\n\n| $k$ | 0 | 1 | 2 | … | 20 | … |\n|:--|:--:|:--:|:--:|:--:|:--:|:--:|\n| $x^k/k!$ | $1$ | $-20$ | $200$ | … | $4.3\\times10^{7}$ | … |\n\nEach term carries a roundoff error of relative size $\\epsilon \\approx 10^{-16}$, i.e. absolute size $\\approx 4\\times10^{-9}$ for the largest terms, which is **as large as the answer itself**. Subtracting nearly equal large numbers leaves only their errors: catastrophic cancellation.\n\nThe function `fexp` below implements the series with a stopping rule based on the relative size of the current term. With `debug = TRUE` it returns the internal steps rather than the final answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\nfexp <- function(x, debug = FALSE) {\n  i <- 0; expx <- 1; u <- 1\n  if (debug) debug_list <- list()\n  while (abs(u) > 1e-20 * abs(expx)) {\n    i <- i + 1\n    u <- u * x / i\n    expx <- expx + u\n    if (debug) debug_list[[i]] <- c(Step = i, Term_u = u, exp_x = expx)\n  }\n  if (debug) return(do.call(rbind, debug_list))\n  expx\n}\n\ntest_vals <- c(10, 20, 60, -1, -10, -20, -50)\nres1 <- data.frame(x = test_vals, Built_in_Exp = exp(test_vals), Taylor_fexp = sapply(test_vals, fexp))\nkable(res1, caption = \"Built-in exp() versus the naive Taylor series fexp()\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Built-in exp() versus the naive Taylor series fexp()\n\n|   x| Built_in_Exp|  Taylor_fexp|\n|---:|------------:|------------:|\n|  10| 2.202647e+04| 2.202647e+04|\n|  20| 4.851652e+08| 4.851652e+08|\n|  60| 1.142007e+26| 1.142007e+26|\n|  -1| 3.678794e-01| 3.678794e-01|\n| -10| 4.540000e-05| 4.540000e-05|\n| -20| 0.000000e+00| 0.000000e+00|\n| -50| 0.000000e+00| 1.107293e+04|\n\n\n:::\n:::\n\n\nFor positive $x$ the series is accurate to all printed digits. For $x = -10$ the answer is already off in the fourth digit, for $x = -20$ it is wrong in the first digit, and `fexp(-50)` yields a completely wrong, negative number. Running it in debug mode shows the massive terms cancelling each other out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndebug_matrix <- fexp(-50, debug = TRUE)\ndebug_summary <- rbind(\n  head(debug_matrix, 10),\n  matrix(NA, nrow = 1, ncol = 3, dimnames = list(\"...\", colnames(debug_matrix))),\n  tail(debug_matrix, 10))\nkable(debug_summary, caption = \"Debug trace for fexp(-50) showing catastrophic cancellation\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Debug trace for fexp(-50) showing catastrophic cancellation\n\n|       | Step|        Term_u|         exp_x|\n|:------|----:|-------------:|-------------:|\n|       |    1| -5.000000e+01| -4.900000e+01|\n|       |    2|  1.250000e+03|  1.201000e+03|\n|       |    3| -2.083333e+04| -1.963233e+04|\n|       |    4|  2.604167e+05|  2.407843e+05|\n|       |    5| -2.604167e+06| -2.363382e+06|\n|       |    6|  2.170139e+07|  1.933801e+07|\n|       |    7| -1.550099e+08| -1.356719e+08|\n|       |    8|  9.688120e+08|  8.331401e+08|\n|       |    9| -5.382289e+09| -4.549149e+09|\n|       |   10|  2.691144e+10|  2.236230e+10|\n|...    |   NA|            NA|            NA|\n|[158,] |  158|  0.000000e+00|  1.107293e+04|\n|[159,] |  159|  0.000000e+00|  1.107293e+04|\n|[160,] |  160|  0.000000e+00|  1.107293e+04|\n|[161,] |  161|  0.000000e+00|  1.107293e+04|\n|[162,] |  162|  0.000000e+00|  1.107293e+04|\n|[163,] |  163|  0.000000e+00|  1.107293e+04|\n|[164,] |  164|  0.000000e+00|  1.107293e+04|\n|[165,] |  165|  0.000000e+00|  1.107293e+04|\n|[166,] |  166|  0.000000e+00|  1.107293e+04|\n|[167,] |  167|  0.000000e+00|  1.107293e+04|\n\n\n:::\n:::\n\n\nThe largest terms reach about $10^{20}$; their roundoff errors are of order $10^{4}$, and the true answer $e^{-50}\\approx 2\\times10^{-22}$ is invisible beneath them.\n\n**Fix by reformulating.** For $x>0$ all terms are positive, so no cancellation occurs. Therefore compute $e^{|x|}$ and invert the result if $x$ was negative:\n$$\ne^{-x} = \\frac{1}{e^{x}}, \\qquad x > 0 .\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfexp2 <- function(x) {\n  xa <- abs(x); i <- 0; expx <- 1; u <- 1\n  while (u > 1e-20 * expx) { i <- i + 1; u <- u * xa / i; expx <- expx + u }\n  if (x >= 0) expx else 1 / expx\n}\n\ntest_vals_neg <- c(-10, -20, -50)\nres2 <- data.frame(x = test_vals_neg, Built_in_Exp = exp(test_vals_neg), Robust_fexp2 = sapply(test_vals_neg, fexp2))\nkable(res2, caption = \"Robust fexp2() for negative arguments\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Robust fexp2() for negative arguments\n\n|   x| Built_in_Exp| Robust_fexp2|\n|---:|------------:|------------:|\n| -10|     4.54e-05|     4.54e-05|\n| -20|     0.00e+00|     0.00e+00|\n| -50|     0.00e+00|     0.00e+00|\n\n\n:::\n:::\n\n\nThe general principle: rearrange a formula so that quantities of similar magnitude and **the same sign** are combined, and avoid computing a small result as the difference of two large numbers.\n\n**A second example of the same principle.** The function $f(x) = e^x - 1$ is needed in interest-rate and survival calculations for small $x$. Computing `exp(x) - 1` directly subtracts two numbers near 1, and for $x = 10^{-10}$ loses six of the sixteen digits; `expm1(x)` uses a series for small $x$ and is exact to machine precision. The same holds for $\\log(1+x)$ and `log1p(x)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1e-10\nc(naive = exp(x) - 1, expm1 = expm1(x), series = x + x^2 / 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n naive  expm1 series \n 1e-10  1e-10  1e-10 \n```\n\n\n:::\n\n```{.r .cell-code}\nx <- 1e-20\nc(naive = log(1 + x), log1p = log1p(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnaive log1p \n0e+00 1e-20 \n```\n\n\n:::\n:::\n\n\n### Computing variance: avoiding large − large\n\nTwo algebraically identical formulas for the sum of squared deviations:\n$$\n\\underbrace{\\sum_{i=1}^{n}(x_i - \\overline{x})^2}_{\\text{two-pass}}\n\\;=\\;\n\\underbrace{\\sum_{i=1}^{n} x_i^2 - \\frac{\\left(\\sum_i x_i\\right)^2}{n}}_{\\text{one-pass}}.\n$$\n\nThe one-pass formula needs only $\\sum x_i$ and $\\sum x_i^2$, computed in a single sweep of the data, which made it attractive for hand calculators and for streaming data. But when the $x_i$ are large and close together, $\\sum x_i^2$ and $(\\sum x_i)^2/n$ are both huge and nearly equal, and the subtraction is large − large.\n\nTake $x = (1, 2, 3)$: the deviations are $(-1, 0, 1)$, so $\\sum(x_i-\\overline x)^2 = 2$. Now shift by $M = 10^{8}$, giving $x = (M+1, M+2, M+3)$. The deviations and the answer are unchanged, but the one-pass formula computes\n$$\n\\sum x_i^2 \\approx 3\\times10^{16}, \\qquad \\frac{(\\sum x_i)^2}{n} \\approx 3\\times10^{16}, \\qquad \\text{difference} = 2.\n$$\nWith 16 significant digits, $3\\times10^{16}$ is stored with a gap of about $4$ between neighbouring representable numbers, so the true answer $2$ lives entirely in the lost digits.\n\n::: {.pv}\n<table>\n<tr><th colspan=\"16\">16 mantissa digits</th><th>lost</th></tr>\n<tr><td class=\"m\">3</td><td class=\"p\">.</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">1</td><td class=\"m\">2</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">0</td><td class=\"m\">1</td><td class=\"x\">4</td><td class=\"p\">×10^16</td></tr>\n</table>\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## one-pass (computational) formula\nvar1 <- function(x) { n <- length(x); (sum(x^2) - sum(x)^2 / n) / (n - 1) }\n\n## two-pass formula (centering on the mean)\nvar2 <- function(x) { n <- length(x); sum((x - mean(x))^2) / (n - 1) }\n\n## small data works fine for both\nx <- c(1, 2, 3)\nc(var1(x), var2(x), var(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 1 1\n```\n\n\n:::\n\n```{.r .cell-code}\n## a large shift exposes catastrophic cancellation in var1\nx <- c(1, 2, 3) + 1e8\nc(var1(x), var2(x), var(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 1 1\n```\n\n\n:::\n\n```{.r .cell-code}\nx <- c(1, 2, 3) + 1e10\nc(var1(x), var2(x), var(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -32768      1      1\n```\n\n\n:::\n:::\n\n\nThe failure sets in gradually. The error of the one-pass formula is of order $\\epsilon\\,M^2 n$, so it becomes visible once $M^2\\epsilon$ is comparable to the true variance, i.e. around $M\\approx 10^{8}$ for a variance of 1. The following scan shows the one-pass result drifting away from 1 and eventually becoming negative, which is impossible for a variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nM <- 10^(0:10)\nres <- t(sapply(M, function(m) { x <- c(1, 2, 3) + m; c(M = m, one_pass = var1(x), two_pass = var2(x)) }))\nkable(res, caption = \"One-pass versus two-pass variance as the data are shifted by M\", digits = 6)\n```\n\n::: {.cell-output-display}\n\n\nTable: One-pass versus two-pass variance as the data are shifted by M\n\n|     M| one_pass| two_pass|\n|-----:|--------:|--------:|\n| 1e+00|        1|        1|\n| 1e+01|        1|        1|\n| 1e+02|        1|        1|\n| 1e+03|        1|        1|\n| 1e+04|        1|        1|\n| 1e+05|        1|        1|\n| 1e+06|        1|        1|\n| 1e+07|        1|        1|\n| 1e+08|        0|        1|\n| 1e+09|        0|        1|\n| 1e+10|   -32768|        1|\n\n\n:::\n:::\n\n#### Fixes {-}\n- **Two-pass**: compute $\\overline x$ first, then $\\sum (x_i - \\overline x)^2$. The deviations are small and of similar size, so no cancellation occurs. This is what `var()` does.\n\n- **Shifted one-pass**: subtract any convenient constant $c \\approx \\overline x$, for instance $c = x_1$, before applying the one-pass formula. The identity\n$$\n\\sum (x_i-\\overline x)^2 = \\sum (x_i - c)^2 - \\frac{\\left(\\sum (x_i - c)\\right)^2}{n},\n$$\nholds for every $c$, and with $c$ near the mean the two terms on the right are no longer huge.\n\n- **Welford's online algorithm** updates the running mean $\\overline x_k$ and running sum of squares $S_k = \\sum_{i\\le k}(x_i - \\overline x_k)^2$ one observation at a time,\n$$\n\\overline x_k = \\overline x_{k-1} + \\frac{x_k - \\overline x_{k-1}}{k}, \\qquad S_k = S_{k-1} + (x_k - \\overline x_{k-1})(x_k - \\overline x_k),\n$$\nand is the method of choice for streaming data, where a two-pass computation is impossible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_shifted <- function(x) { n <- length(x); d <- x - x[1]; (sum(d^2) - sum(d)^2 / n) / (n - 1) }\n\nvar_welford <- function(x) {\n  m <- 0; S <- 0\n  for (k in seq_along(x)) { m_old <- m; m <- m + (x[k] - m) / k; S <- S + (x[k] - m_old) * (x[k] - m) }\n  S / (length(x) - 1) }\n\nx <- c(1, 2, 3) + 1e10\nc(one_pass = var1(x), shifted = var_shifted(x), welford = var_welford(x), two_pass = var2(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\none_pass  shifted  welford two_pass \n  -32768        1        1        1 \n```\n\n\n:::\n:::\n\n\n## Methods for Mitigating Overflow and Underflow Errors\n\n### Where overflow and underflow arise in statistics\n\nLikelihoods are **products of many probabilities**, and normalizing constants involve **factorials** or **exponentials**:\n$$\n\\prod_{i=1}^{2000} p(x_i) = \\left(\\tfrac12\\right)^{2000} \\approx 10^{-602} \\quad\\to\\quad \\text{underflow to } 0,\n$$\n$$\n1000! \\approx 4\\times10^{2567} \\quad\\to\\quad \\text{overflow to } \\infty,\n$$\n$$\n\\text{logistic: } \\frac{e^{x}}{1+e^{x}} \\text{ at } x = 1000 \\quad\\to\\quad \\frac{\\infty}{\\infty} = \\texttt{NaN}.\n$$\n\nTwo remedies are available: change the algebraic expression so that the intermediate quantities stay in range, or work on the logarithmic scale.\n\n### Changing the algebraic expression\n\nTwo equivalent forms of the logistic (sigmoid) function:\n$$\n\\sigma(x) = \\frac{e^{x}}{1+e^{x}} = \\frac{1}{1+e^{-x}}.\n$$\n\n| $x$ | $e^{x}/(1+e^{x})$ | $1/(1+e^{-x})$ |\n|:--:|:--|:--|\n| $+1000$ | $e^{x}=\\infty$, $\\infty/\\infty = $ `NaN` ✗ | $e^{-x}=0$, $1/1 = 1$ ✓ |\n| $-1000$ | $e^{x}=0$, $0/1 = 0$ ✓ | $e^{-x}=\\infty$, $1/\\infty = 0$ ✓ |\n\nEvaluating the first form at a large positive value yields $\\infty/\\infty$; the second form lets $e^{-x}$ underflow harmlessly to $0$ and computes $1/(1+0) = 1$. In this case the second form is safe at both ends, because a division by $\\infty$ gives $0$ correctly. In general one picks the form in which the exponential has a **non-positive** argument:\n$$\n\\sigma(x) = \\begin{cases} 1/(1+e^{-x}) & x \\ge 0\\\\ e^{x}/(1+e^{x}) & x < 0.\\end{cases}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- function(theta) exp(theta) / (1 + exp(theta))\np2 <- function(theta) 1 / (1 + exp(-theta))\n\n## large positive theta breaks p1, works in p2\ntheta <- 2000\nc(p1 = p1(theta), p2 = p2(theta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n p1  p2 \nNaN   1 \n```\n\n\n:::\n\n```{.r .cell-code}\n## large negative theta works for both\ntheta <- -2000\nc(p1 = p1(theta), p2 = p2(theta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np1 p2 \n 0  0 \n```\n\n\n:::\n\n```{.r .cell-code}\n## the piecewise form is safe everywhere and keeps full precision in both tails\nsigmoid <- function(x) ifelse(x >= 0, 1 / (1 + exp(-x)), exp(x) / (1 + exp(x)))\nsigmoid(c(-2000, -20, 0, 20, 2000))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000000e+00 2.061154e-09 5.000000e-01 1.000000e+00 1.000000e+00\n```\n\n\n:::\n:::\n\n\n**Built-in functions.** Software provides functions written specifically to avoid cancellation and overflow, and they should be used in preference to the naive composition:\n\n| instead of | use | reason |\n|:--|:--|:--|\n| `log(1 + x)` | `log1p(x)` | for tiny $x$, `1 + x` rounds to 1 |\n| `exp(x) - 1` | `expm1(x)` | for tiny $x$, `exp(x)` rounds to 1 |\n| `log(factorial(n))` | `lfactorial(n)`, `lgamma(n + 1)` | `factorial(n)` overflows |\n| `log(choose(n, k))` | `lchoose(n, k)` | overflow |\n| `log(dnorm(x))` | `dnorm(x, log = TRUE)` | `dnorm(x)` underflows |\n| `log(pnorm(x))` | `pnorm(x, log.p = TRUE)` | underflow |\n| `log(1 - pnorm(x))` | `pnorm(x, lower.tail = FALSE, log.p = TRUE)` | cancellation and underflow |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(naive = log(factorial(1000)), lfactorial = lfactorial(1000))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     naive lfactorial \n       Inf   5912.128 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(naive = log(dnorm(40)), dnorm_log = dnorm(40, log = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    naive dnorm_log \n     -Inf -800.9189 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(naive = log(1 - pnorm(10)), stable = pnorm(10, lower.tail = FALSE, log.p = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    naive    stable \n     -Inf -53.23129 \n```\n\n\n:::\n:::\n\n\nThe last line shows both failures at once: `1 - pnorm(10)` is `1 - 1 = 0` in double precision, so the naive answer is `-Inf`, while the true value is about $-53.2$.\n\n### Representing numbers in logarithmic form\n\nRepresent a positive number $x$ by $\\ell_x = \\log x$:\n$$\nx = e^{2000} \\iff \\ell_x = 2000, \\qquad x = e^{-2000} \\iff \\ell_x = -2000 .\n$$\nNumbers that overflow or underflow in ordinary form are ordinary numbers on the log scale. The cost is that each operation $f$ must be **translated** to the log scale:\n$$\nx_1,\\dots,x_n \\xrightarrow{\\;f\\;} y \\qquad\\Longleftrightarrow\\qquad \\ell_1,\\dots,\\ell_n \\xrightarrow{\\;\\tilde f\\;} \\ell_y = \\log f(e^{\\ell_1},\\dots,e^{\\ell_n}).\n$$\n\n**Products and quotients** are the easy case:\n$$\n\\log(x_1 x_2) = \\ell_1 + \\ell_2, \\qquad \\log\\left(\\prod_{i=1}^{n} x_i\\right) = \\sum_{i=1}^{n} \\ell_i, \\qquad \\log\\frac{x_1}{x_2} = \\ell_1 - \\ell_2.\n$$\nIn particular $\\log \\prod_i p(x_i) = \\sum_i \\log p(x_i)$: always compute the log-likelihood, never the likelihood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_x <- 800; x <- exp(log_x); x          # overflow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Inf\n```\n\n\n:::\n\n```{.r .cell-code}\nlog_y <- 805; y <- exp(log_y); y          # overflow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Inf\n```\n\n\n:::\n\n```{.r .cell-code}\nx / y                                     # Inf/Inf = NaN\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NaN\n```\n\n\n:::\n\n```{.r .cell-code}\nlog_xovery <- log_x - log_y               # subtracting logs is safe\nlog_xovery\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -5\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(log_xovery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.006737947\n```\n\n\n:::\n\n```{.r .cell-code}\n## likelihood versus log-likelihood for 2000 fair-coin tosses\np <- rep(0.5, 2000)\nc(likelihood = prod(p), log_likelihood = sum(log(p)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    likelihood log_likelihood \n         0.000      -1386.294 \n```\n\n\n:::\n:::\n\n\n### The log-sum-exp trick\n\nSums are the hard case: $\\log(x_1 + x_2) \\neq \\ell_1 + \\ell_2$. We need\n$$\n\\log\\left(\\sum_{i=1}^{n} x_i\\right) = \\log\\left(\\sum_{i=1}^{n} e^{\\ell_i}\\right),\n$$\nbut the $e^{\\ell_i}$ may overflow or underflow. Let $m = \\max_i \\ell_i$ and factor it out:\n$$\n\\log\\left(\\sum_{i=1}^{n} e^{\\ell_i}\\right)\n= \\log\\left(e^{m}\\sum_{i=1}^{n} e^{\\ell_i - m}\\right)\n= m + \\log\\left(\\sum_{i=1}^{n} e^{\\ell_i - m}\\right).\n$$\n\nEvery $\\ell_i - m \\le 0$, so $e^{\\ell_i - m} \\in (0, 1]$ and nothing overflows; the largest term is $e^{0} = 1$, so the sum is at least 1 and cannot underflow. Terms far below the maximum underflow to $0$ individually, but they would have contributed nothing at 16-digit precision anyway.\n\nIllustration with $x_i = e^{2000}, e^{2001}, e^{2002}$, each of which overflows to `Inf`:\n\n| | $i=1$ | $i=2$ | $i=3$ |\n|:--|:--:|:--:|:--:|\n| $\\ell_i$ | 2000 | 2001 | 2002 |\n| $\\ell_i - m$ ($m = 2002$) | $-2$ | $-1$ | $0$ |\n| $e^{\\ell_i - m}$ | $0.135$ | $0.368$ | $1$ |\n$$\n\\log\\sum_i x_i = 2002 + \\log(0.135 + 0.368 + 1) = 2002.408\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_sum_exp <- function(log_x) {\n  max_log_x <- max(log_x)\n  max_log_x + log(sum(exp(log_x - max_log_x)))\n}\n\n## values that would overflow directly\nlog_x <- c(2000, 2010, 2030)\nexp(log_x)                                   # Inf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Inf Inf Inf\n```\n\n\n:::\n\n```{.r .cell-code}\nc(direct = log(sum(exp(log_x))), lse = log_sum_exp(log_x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndirect    lse \n   Inf   2030 \n```\n\n\n:::\n\n```{.r .cell-code}\n## values that would underflow directly\nlog_x <- -c(2000, 2010, 2030)\nexp(log_x)                                   # 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 0 0\n```\n\n\n:::\n\n```{.r .cell-code}\nc(direct = log(sum(exp(log_x))), lse = log_sum_exp(log_x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndirect    lse \n  -Inf  -2000 \n```\n\n\n:::\n:::\n\n\n**Example: log-likelihood of a mixture.** The density of a two-component normal mixture is $f(y) = \\pi_1\\varphi(y;\\mu_1,1) + \\pi_2\\varphi(y;\\mu_2,1)$, a sum inside a product. For an observation far from both means, both component densities underflow and the naive log-likelihood is `-Inf`; with log-sum-exp applied observation by observation it is finite and correct.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(-1, 0.5, 2, 45)                      # the last value is far from both means\nmu <- c(0, 3); w <- c(0.6, 0.4)\nnaive <- sum(log(w[1] * dnorm(y, mu[1]) + w[2] * dnorm(y, mu[2])))\nstable <- sum(sapply(y, function(yi) log_sum_exp(log(w) + dnorm(yi, mu, log = TRUE))))\nc(naive = naive, stable = stable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    naive    stable \n     -Inf -889.3333 \n```\n\n\n:::\n:::\n\n\n**Example: log-softmax.** The softmax probabilities $p_k = e^{x_k}/\\sum_j e^{x_j}$ appear in multinomial logistic regression and neural networks. Their logarithm is $\\log p_k = x_k - \\log\\sum_j e^{x_j}$, and the second term is a log-sum-exp.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(1000, 1001, 1005)\nnaive <- log(exp(x) / sum(exp(x)))\nstable <- x - log_sum_exp(x)\nrbind(naive, stable, probabilities = exp(stable))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      [,1]        [,2]        [,3]\nnaive                  NaN         NaN         NaN\nstable        -5.024744890 -4.02474489 -0.02474489\nprobabilities  0.006573263  0.01786798  0.97555875\n```\n\n\n:::\n:::\n\n\n### Differences on the log scale\n\nFor $x > y > 0$ with $\\ell_x = \\log x$, $\\ell_y = \\log y$:\n$$\n\\log(x - y) = \\log\\left(e^{\\ell_x}\\left(1 - e^{\\ell_y - \\ell_x}\\right)\\right) = \\ell_x + \\log\\left(1 - e^{\\ell_y - \\ell_x}\\right).\n$$\nSince $\\ell_y - \\ell_x < 0$, $e^{\\ell_y-\\ell_x}\\in(0,1)$ and there is no overflow. When $x \\approx y$, the factor $1 - e^{\\ell_y-\\ell_x}$ is itself a large − large subtraction; `log1p(-exp(ly - lx))` avoids it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_minus_exp <- function(log_x, log_y) {\n  if (log_x < log_y) stop(\"the first argument must be the larger\")\n  log_x + log1p(-exp(log_y - log_x))\n}\n\nlog_minus_exp(2020, 2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2020\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(2000) - exp(1999)                       # direct subtraction: Inf - Inf = NaN\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NaN\n```\n\n\n:::\n\n```{.r .cell-code}\n## nearly equal arguments: log1p keeps the precision that log(1 - .) would lose\nlx <- 10; ly <- 10 - 1e-12\nc(with_log1p = log_minus_exp(lx, ly), with_log = lx + log(1 - exp(ly - lx)), exact = log(exp(lx) - exp(ly)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwith_log1p   with_log      exact \n -17.63093  -17.63093  -17.63079 \n```\n\n\n:::\n:::\n\n\nA statistical use of the difference formula is the survival function of a discrete distribution, $\\log P(X > k) = \\log\\big(1 - P(X\\le k)\\big)$, when $P(X\\le k)$ is available only as a log-probability close to $0$.\n\n## Summary\n\n- Integers occupy a fixed number of bits; exceeding $2^{31}-1$ gives `NA` in R.\n\n- Doubles store a sign, a 52-bit mantissa (about 16 decimal digits), and an 11-bit exponent (magnitudes $10^{-308}$ to $10^{308}$). Neighbouring doubles are spaced at a relative distance of about $\\epsilon = 2^{-52}$; integers above $2^{53}$ are not all representable.\n- Overflow produces `Inf`, underflow produces `0`; the latter is silent and therefore more dangerous.\n\n- Roundoff error is amplified by adding large + small (fix: add small terms first, pairwise or compensated summation) and by subtracting large − large (fix: reformulate so that same-sign quantities of similar size are combined, as in $e^{-x} = 1/e^{x}$ and the two-pass variance).\n- Overflow and underflow are avoided by rewriting expressions so that exponentials have non-positive arguments, by using purpose-built functions (`log1p`, `expm1`, `lgamma`, `dnorm(log = TRUE)`), and by working on the log scale, where products become sums and sums are handled by the log-sum-exp trick.\n\n## Exercises\n\n**Question 1.** How do you compute\n$$\n\\log\\left(\\frac{1}{1+e^{-x}}\\right),\n$$\nso as to avoid overflow and underflow of $e^{-x}$, for both large positive and large negative $x$? (Hint: write it as $-\\log(1+e^{-x})$ and consider `log1p` and the two forms of the sigmoid.)\n\n**Question 2 (log-softmax).** How do you compute\n$$\n\\log\\left(\\frac{e^{x_k}}{\\sum_{j=1}^{K} e^{x_j}}\\right),\n$$\nso as to avoid underflow and overflow of $e^{x_j}$? Verify your formula against the `log-softmax` example above for $x = (1000, 1001, 1005)$ and for $x = (-1000, -1001, -1005)$.\n\n**Question 3.** The one-pass variance formula fails for $x = (M+1, M+2, M+3)$ with $M = 10^{8}$. Predict the smallest $M$ (a power of 10) at which the one-pass result in R first differs from $2$, then verify using the scan in the variance section.\n\n**Question 4.** Write a function `log_dbinom(k, n, p)` that returns $\\log\\binom{n}{k}p^k(1-p)^{n-k}$ for $n = 10^5$ without overflow or underflow, using `lchoose` and `log1p`, and compare it with `dbinom(k, n, p, log = TRUE)`.\n\n**Question 5.** Implement Welford's algorithm for the sample covariance of two variables and check it against `cov()` on data shifted by $10^{10}$.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}